apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "atala-prism-dev-deployments-github-docker-registry-key"
  namespace: {{ .Release.Namespace }}
  labels:
      {{ template "labels.common" . }}
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: {{ .Values.secretStore }}
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ `{{ .dockerconfigjson | b64dec }}` }}"
  dataFrom:
    - extract:
        key: {{ .Values.dockerRegistryToken }}

---
# Requires wallet to be created (atm it's done through terraform module)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Values.vdr.cardanoNode }}-{{ .Values.vdr.cardanoWallet }}"
  namespace: {{ .Release.Namespace }}
  labels:
      {{ template "labels.common" . }}
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: {{ .Values.secrets.secretStore }}
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: {{ .Values.vdr.cardanoWallet }}
