@startuml
title Bitcoin - Holder recovering data

actor Holder
participant "Holder Wallet" as HolderWallet
participant IOHK
actor Issuer

Holder -> HolderWallet : Recover data
HolderWallet -> Holder : Ask for recovery seed
Holder -> HolderWallet : Enter recovery seed
HolderWallet -> HolderWallet : Deterministically generate private keys
HolderWallet -> IOHK : Look for existing connections
IOHK -> HolderWallet : Got existing connections

Holder -> Issuer : Ask to resend existing certificates
note right of Holder : Holder goes to the Issuer offices, which prevents attackers\n to access holder credentials if they compromise the holder recovery seed
Issuer -> Issuer : Validate holder request and identity
Issuer -> IOHK : Submit certificates to the holder
note over Issuer : The same connection that was used while issuing\n the certificate is used again
IOHK -> HolderWallet : Existing certificates recovered
HolderWallet -> HolderWallet : Store recovered certificates
HolderWallet -> Holder : Display recovered data
@enduml