{
 "title": "Management-console",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ComponentName", "query": "management-console" },
   { "name": "Env", "label": "Job/Envirement", "query": { "query": "label_values(job)" } },
   {
    "name": "Service",
    "query": {
     "query": "label_values(request_time_seconds_bucket{job=~\".*$Env-$ComponentName.*\"}, service)"
    }
   },
   {
    "name": "Repository",
    "query": {
     "query": "label_values(db_query_time_seconds_bucket{job=~\".*$Env-$ComponentName.*\"}, repository)"
    }
   },
   {
    "name": "DBMethod",
    "query": {
     "query": "label_values(db_query_time_seconds_bucket{job=~\".*$Env-$ComponentName.*\"}, method)"
    }
   },
   {
    "name": "ServiceMethod",
    "query": {
     "query": "label_values(request_time_seconds_bucket{job=~\".*$Env-$ComponentName.*\"}, method)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "JVM uptime",
   "type": "graph",
   "description": "Uptime of the JVM",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "jvm_uptime_seconds_total{job=~\".*$Env-$ComponentName.*\"}",
     "legendFormat": "Job:[{{job}}] Instance:[{{instance}}]"
    }
   ]
  },
  {
   "title": "The number of JVM uptime reporters",
   "type": "graph",
   "description": "\nThe number of online instances (those who have JVM uptime metric) per job (environment). Because it uses the jvm_uptime metric, there is a possibility that you will not see environments where JVM can't go online (continuous restarts etc).",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(count(jvm_uptime_seconds_total{job=~\".*$Env-$ComponentName.*\"}) by (job)) > 0",
     "legendFormat": "Job:[{{job}}]"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "graph",
   "description": "The percentage of ram usage by host",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(host_memory_usage{job=~\".*$Env-$ComponentName.*\"}) by (job, instance)",
     "legendFormat": "Job:[{{job}}] Instance:[{{instance}}]"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Percentage of average CPU usage by host",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(host_load_average{job=~\".*$Env-$ComponentName.*\"}) by (job, interval, instance)",
     "legendFormat": "Job:[{{job}}] Instance:[{{instance}}]"
    }
   ]
  },
  {
   "title": "Service errors by JVM",
   "type": "graph",
   "description": "Just total number of current server errors - total number of server errors by offset",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(error_count_total{job=~\".*$Env-$ComponentName.*\", service=~\"$Service\", method=~\"$ServiceMethod\"} - (error_count_total{job=~\".*$Env-$ComponentName.*\", service=~\"$Service\", method=~\"$ServiceMethod\"} offset $__interval))",
     "legendFormat": "Code:[{{error_code}}]  Service:[{{service}}] Method:[{{method}}] Instance:[{{instance}}] Job:[{{job}}]"
    }
   ]
  },
  {
   "title": "GRPC Success rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum (rate(envoy_cluster_grpc_iohk_atala_prism_protos_ConsoleService_success{job=~\".*$Env.*\"}[$__interval]))) / (sum (rate(envoy_cluster_grpc_iohk_atala_prism_protos_ConsoleService_total{job=~\".*$Env.*\"}[$__interval])))",
     "legendFormat": "Console service"
    },
    {
     "expr": "(sum (rate(envoy_cluster_grpc_iohk_atala_prism_protos_ContactsService_success{job=~\".*$Env.*\"}[$__interval]))) / (sum (rate(envoy_cluster_grpc_iohk_atala_prism_protos_ContactsService_total{job=~\".*$Env.*\"}[$__interval])))",
     "legendFormat": "Contacts service"
    },
    {
     "expr": "(sum (rate(envoy_cluster_grpc_iohk_atala_prism_protos_CredentialIssuanceService_success{job=~\".*$Env.*\"}[$__interval]))) / (sum (rate(envoy_cluster_grpc_iohk_atala_prism_protos_ContactsService_total{job=~\".*$Env.*\"}[$__interval])))",
     "legendFormat": "Credential issuance service"
    },
    {
     "expr": "(sum (rate(envoy_cluster_grpc_iohk_atala_prism_protos_CredentialsService_success{job=~\".*$Env.*\"}[$__interval]))) / (sum (rate(envoy_cluster_grpc_iohk_atala_prism_protos_CredentialsService_total{job=~\".*$Env.*\"}[$__interval])))",
     "legendFormat": "Credentials service"
    },
    {
     "expr": "(sum (rate(envoy_cluster_grpc_iohk_atala_prism_protos_CredentialsStoreService_success{job=~\".*$Env.*\"}[$__interval]))) / (sum (rate(envoy_cluster_grpc_iohk_atala_prism_protos_CredentialsStoreService_total{job=~\".*$Env.*\"}[$__interval])))",
     "legendFormat": "Credentials store service"
    },
    {
     "expr": "(sum (rate(envoy_cluster_grpc_iohk_atala_prism_protos_CredentialTypesService_success{job=~\".*$Env.*\"}[$__interval]))) / (sum (rate(envoy_cluster_grpc_iohk_atala_prism_protos_CredentialsStoreService_total{job=~\".*$Env.*\"}[$__interval])))",
     "legendFormat": "Credential types service"
    },
    {
     "expr": "(sum (rate(envoy_cluster_grpc_iohk_atala_prism_protos_GroupsService_success{job=~\".*$Env.*\"}[$__interval]))) / (sum (rate(envoy_cluster_grpc_iohk_atala_prism_protos_GroupsService_total{job=~\".*$Env.*\"}[$__interval])))",
     "legendFormat": "Groups service"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "graph",
   "description": "Percentile 50",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_time_seconds_bucket{job=~\".*$Env-$ComponentName.*\",service=~\"$Service\", method=~\"$ServiceMethod\"}[$__interval])) by (job, service, method, le)) >= 0",
     "legendFormat": "Service:[{{service}}] Method:[{{method}}] Job:[{{job}}]"
    }
   ]
  },
  {
   "title": "Storage usage",
   "type": "graph",
   "description": "The percentage of occupied storage memory",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "host_storage_mount_space_usage{job=~\".*$Env-$ComponentName.*\", mount=\"/etc/hostname\"}",
     "legendFormat": "Job:[{{job}}] Instance:[{{instance}}]"
    }
   ]
  },
  {
   "title": "Response time 90 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(request_time_seconds_bucket{job=~\".*$Env-$ComponentName.*\",service=~\"$Service\", method=~\"$ServiceMethod\"}[$__interval])) by (job, service, method, le)) >= 0",
     "legendFormat": "Service:[{{service}}] Method:[{{method}}] Job:[{{job}}]"
    }
   ]
  },
  {
   "title": "Response time 99 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_time_seconds_bucket{job=~\".*$Env-$ComponentName.*\",service=~\"$Service\", method=~\"$ServiceMethod\"}[$__interval])) by (job, service, method,le)) >= 0",
     "legendFormat": "Service:[{{service}}] Method:[{{method}}] Job:[{{job}}]"
    }
   ]
  },
  {
   "title": "DB query time 90 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(db_query_time_seconds_bucket{job=~\".*$Env-$ComponentName.*\",repository=~\"$Repository\", method=~\"$DBMethod\"}[$__interval])) by (job, repository, method, le)) >= 0",
     "legendFormat": "Repository:[{{repository}}] Method:[{{method}}] Job:[{{job}}] "
    }
   ]
  },
  {
   "title": "DB query time 99 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(db_query_time_seconds_bucket{job=~\".*$Env-$ComponentName.*\",repository=~\"$Repository\", method=~\"$DBMethod\"}[$__interval])) by (job, repository, method, le)) >= 0",
     "legendFormat": "Repository:[{{repository}}] Method:[{{method}}] Job:[{{job}}] "
    }
   ]
  },
  {
   "title": "Concurrent requests",
   "type": "graph",
   "description": "Number of in-flight requests on metrics collection moment",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "active_requests{job=~\".*$Env-$ComponentName.*\", service=~\"$Service\", method=~\"$ServiceMethod\"} > 0",
     "legendFormat": "Service:[{{service}}] Method:[{{method}}] Job:[{{job}}]"
    }
   ]
  },
  {
   "title": "Number of requests",
   "type": "graph",
   "description": "Just total number of current requests - total number of requests by offset",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(request_time_seconds_count{job=~\".*$Env-$ComponentName.*\", service=~\"$Service\", method=~\"$ServiceMethod\"} - (request_time_seconds_count{job=~\".*$Env-$ComponentName.*\", service=~\"$Service\", method=~\"$ServiceMethod\"} offset $__interval)) > 0",
     "legendFormat": "Service:[{{service}}] Method:[{{method}}] Job:[{{job}}]"
    }
   ]
  }
 ]
}