@startuml
title Bitcoin - Issue credential

participant GEUD
actor University
participant IOHK
actor Student

University -> University : Unlocks cold storage key
University -> University : Find student's DID and personal details
University -> University : Issue and store the credential
University -> GEUD : Store proof-of-existence
GEUD -> University : Proof stored
University -> IOHK : Share credential
IOHK -> IOHK : Verifies the university is\n connected to the student
IOHK -> IOHK : Store the credential
IOHK -> University : Ack
IOHK -> Student : Share credential once it gets online
Student -> IOHK : Ack
Student -> Student : Verify credential validity
Student -> Student : Store credential
@enduml