@startuml
title Bitcoin - University wallet preparation

participant IOHK
actor University

University -> Wallet : Create wallet
Wallet -> University : Wallet created

University -> Wallet : Generate DID
Wallet -> Wallet : Creates and stores a DID
Wallet -> University : DID generated

University -> Wallet : Publish DID
Wallet -> GEUD : Publish DID
GEUD -> Wallet : DID published
Wallet -> University : DID published

University -> IOHK : Register DID
IOHK -> University : DID registered

University -> IOHK : Choose billing plan\n (Who pays for connections)
IOHK -> University : Billing plan defined

note over University : The University will likely issue\n credentials in batches,\n possibly twice a year\n having the key in cold storage is\n a safe mechanism for protecting it\n to prevent getting it compromised
University -> University : Backup DID private key\n preferably on cold storage
University -> Wallet : Delete DID private key
Wallet -> University : Private key deleted
@enduml