@startuml
title Bitcoin - Issuer Wallet preparation

participant IOHK
actor Issuer
participant "Issuer IssuerWallet" as IssuerWallet
participant "ATALA Node" as AtalaNode

Issuer -> IssuerWallet : Create Wallet
IssuerWallet -> Issuer : Wallet created

Issuer -> IssuerWallet : Generate DID
IssuerWallet -> IssuerWallet : Creates and stores a DID
IssuerWallet -> Issuer : DID generated

Issuer -> IssuerWallet : Publish DID
IssuerWallet -> AtalaNode : Publish DID
AtalaNode -> IssuerWallet : DID published
IssuerWallet -> Issuer : DID published

Issuer -> IOHK : Register DID
IOHK -> Issuer : DID registered

Issuer -> IOHK : Choose billing plan\n (Who pays for connections)
IOHK -> Issuer : Billing plan defined

note over Issuer : The Issuer will likely issue\n credentials in batches,\n possibly twice a year\n having the key in cold storage is\n a safe mechanism for protecting it\n to prevent getting it compromised
Issuer -> Issuer : Backup DID private key\n preferably on cold storage
Issuer -> IssuerWallet : Delete DID private key
IssuerWallet -> Issuer : Private key deleted
@enduml