@startuml

title Prism Architecture

left to right direction

skinparam {
    ArrowColor Red
    linetype ortho
}

skinparam cloud {
  BorderColor Black
}

cloud "IOHK Cloud" as IOHKCloud {
    rectangle Connector {
        node "Connector Server" as ConnectorServer
        database "Connector Database" as ConnectorDatabase
        ConnectorServer --> ConnectorDatabase
    }

    rectangle "Management Console Backend" as ManagementConsole {
        node "Management Console Server" as ManagementConsoleServer
        database "Management Console Database" as ManagementConsoleDatabase
        ManagementConsoleServer --> ManagementConsoleDatabase
    }

    rectangle Node {
        node Cardano
        node "Prism Node" as PrismNode
        database "Prism Node Database" as PrismNodeDatabase
        PrismNode --> PrismNodeDatabase
        PrismNode ---> Cardano
    }

    rectangle Frontend {
        node "Reverse Proxy" as ReverseProxy
        node "Management Console WebApp" as WebApp
    }

    ReverseProxy ---> ConnectorServer
    ReverseProxy ---> ManagementConsoleServer
    ReverseProxy ---> PrismNode
    ManagementConsoleServer -left-> ConnectorServer
    ManagementConsoleServer --left--> PrismNode
}

rectangle "Issuer Computer" as IssuerComputer {
    [Prism Wallet] as BrowserWallet
    [Management Console WebApp] as IssuerWebApp
    IssuerWebApp -> BrowserWallet
    IssuerWebApp -left-> ReverseProxy
}

rectangle "Verifier Computer" as VerifierComputer {
    [Prism Wallet] as VerifierWallet
    [Management Console WebApp] as VerifierWebApp
    VerifierWebApp -> VerifierWallet
    VerifierWebApp --> ReverseProxy
}

HolderPhone -[hidden]- IOHKCloud

rectangle "Holder Phone" as HolderPhone {
    [Mobile Wallet] as MobileWallet
    MobileWallet -> ReverseProxy
}

@enduml