{{- if and (.Values.ingress.enabled) (.Values.server.legacyMode) }}
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: node-route
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{ template "labels.common" . }}
spec:
  http:
  - name: node-rule
    match:
      hosts:
        {{- range .Values.ingress.applicationUrls }}
        - {{ . }}
      {{- end }}
      paths:
      - /*
    backends:
       - serviceName: node-service
         servicePort: 50053
         resolveGranularity: service
    plugins:
        - name: redirect
          enable: true
          config:
            http_to_https: true
{{- end -}}
