apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "atala-prism-dev-deployments-github-docker-registry-key"
  namespace: {{ .Release.Namespace }}
  labels:
      {{ template "labels.common" . }}
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: {{ .Values.secrets.secretStore }}
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ `{{ .dockerconfigjson | b64dec }}` }}"
  dataFrom:
    - extract:
        key: {{ .Values.secrets.dockerRegistryToken }}
---
{{- if and (empty .Values.vdr.externalResources.wallet.host)
           (empty .Values.vdr.externalResources.db_sync.host) }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Values.vdr.cardanoNode }}-{{ .Values.vdr.cardanoWallet }}"
  namespace: {{ .Release.Namespace }}
  labels:
      {{ template "labels.common" . }}
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: {{ .Values.secrets.secretStore }}
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: {{ .Values.vdr.cardanoWallet }}
---
{{- end }}
{{- if not (empty .Values.vdr.externalResources.wallet.host) }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Values.secrets.cardanoWallet }}"
  namespace: {{ .Release.Namespace }}
  labels:
      {{ template "labels.common" . }}
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: {{ .Values.secrets.secretStore }}
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: "{{ .Values.secrets.cardanoWallet }}"
---
{{- end }}
{{- if not (empty .Values.vdr.externalResources.db_sync.host) }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Values.secrets.cardanoDbSync }}"
  namespace: {{ .Release.Namespace }}
  labels:
      {{ template "labels.common" . }}
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: {{ .Values.secrets.secretStore }}
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: "{{ .Values.secrets.cardanoDbSync }}"
---
{{- end }}
