apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: "{{ .Values.database.postgres.managingTeam }}-prism-node-postgres-cluster"
  namespace: {{ .Release.Namespace }}
  labels:
    {{ template "labels.common" . }}
spec:
  teamId: "{{ .Values.database.postgres.managingTeam }}"
  volume:
    size: "{{ .Values.database.postgres.databaseSize }}"
  numberOfInstances: {{ .Values.database.postgres.numberOfInstances }}
  users:
    prism-admin:
      - superuser
      - createdb
    prism-application-user: []
  databases:
    prism: prism-admin
  postgresql:
    version: "14"
{{- if .Values.database.postgres.metrics.enabled }}
  sidecars:
    - name: exporter
      image: "{{ .Values.database.postgres.metrics.image.repository }}/{{ .Values.database.postgres.metrics.image.tag }}:{{ .Values.database.postgres.metrics.image.version }}"
      args:
        - --collector.stat_statements
      ports:
        - name: exporter
          containerPort: 9187
          protocol: TCP
      resources:
        limits:
          cpu: 500m
          memory: 256M
        requests:
          cpu: 100m
          memory: 256M
      env:
        - name: DATA_SOURCE_URI
          value: "127.0.0.1:5432"
        - name: DATA_SOURCE_USER
          value: "$(POSTGRES_USER)"
        - name: DATA_SOURCE_PASS
          value: "$(POSTGRES_PASSWORD)"
{{- end }}
