load("//scala:rules.bzl", "scala_library")

scala_library(
    name = "models",
    external = [
    ],
    deps = [
        "//atala/clock",
        "@multicrypto//src/io/iohk/multicrypto",
        "@multicrypto//src/io/iohk/multicrypto/error",
    ],
)
