CircleCI:
  - .circleci/**/*
GitHub:
  - .github/**/*
ROOT:
  - ./*
backend:
  - prism-backend/**/*
connector:
  - prism-backend/connector/**/*
  - prism-backend/infra/modules/components/prism-connector/**/*
node:
  - prism-backend/node/**/*
  - prism-backend/infra/modules/components/prism-node/**/*
mirror:
  - prism-backend/mirror/**/*
  - prism-backend/infra/modules/components/prism-mirror/**/*
vault:
  - prism-backend/vault/**/*
  - prism-backend/infra/modules/components/prism-vault/**/*
docs:
  - prism-backend/docs/**/*
infra:
  - prism-backend/infra/**/*
envoy:
  - prism-backend/infra/modules/components/prism-envoy/**/*
android-wallet:
  - prism-android-wallet/**/*
ios-wallet:
  - prism-ios-wallet/**/*
web-wallet:
  - prism-web-wallet/**/*
kotlin-sdk:
  - prism-kotlin-sdk/**/*
scala-sdk:
  - prism-sdk/**/*
interactive-demo:
  - prism-interactive-demo-web/**/*
