ingress:
  enabled: true
  applicationUrls:
  - chart-base-prism-stack.atalaprism.io
  platformIngressUrl: chart-base-platform-ingress.atalaprism.io
  cors:
    enabled: true
    allow_origins: "*"
  consumers: []

secrets:
  secretStore: chart-base-secretstore
  dockerRegistryToken: chart-base-docker-registry-token
  cardanoSecret: demeter-preprod-v2

server:
  ledger: "cardano"
  genesisBlock: 424661
  moveScheduledToPendingPeriod: 3s
  refereshAndSubmitPeriod: 3s
  confirmationBlocks: 1
  legacyMode: false
  image:
    repository: ghcr.io
    pullPolicy: IfNotPresent
    tag: input-output-hk/prism-node
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  additionalEnvVariables: []

database:
  postgres:
    managingTeam: atala
    databaseSize: 4Gi
    numberOfInstances: 2

vdr:
  externalResources:
    wallet:
      # host: 8090-cardano-wallet-preprod-bdj2f7.workloads-m1.demeter.run
      # port: 8090
      tls: false
    # db_sync:
    #   database": FIXME
    #   host": FIXME
    #   password": FIXME
    #   username": FIXME
  cardanoNode: atala-cardano-dev-preprod
  cardanoNamespace: cardano-stack
  cardanoWallet: dev-k8s-cardano-wallet

nginx:
  serverBlock: |-
    server {
      listen 8080;
      location / {
        resolver 8.8.8.8;
        proxy_pass https://8090-cardano-wallet-preprod-bdj2f7.workloads-m1.demeter.run$uri$is_args$args;
      }
    }
  
