version: "3"
services:

  cvp-envoy:
    build:
      context: cvp-envoy
    ports:
      - 127.0.0.1:8080:8080

  bitcoind:
    image: ruimarinho/bitcoin-core
    command:
      -printtoconsole
      -regtest=1
      -rpcallowip=0.0.0.0/0
      -rpcuser=bitcoin
      -rpcpassword=bitcoin
      -rpcbind=bitcoind:18333
    ports:
      - 127.0.0.1:18333:18333

  postgres:
    build:
      context: cvp-postgres
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

  connector:
    build:
      context: ../../out/connector/docker-build/dest
      dockerfile: ../../../../connector/Dockerfile
    ports:
      - 127.0.0.1:50051:50051
    depends_on:
      - postgres
    environment:
      GEUD_CONNECTOR_PSQL_HOST: postgres
      GEUD_CONNECTOR_PSQL_DATABASE: connector
      GEUD_CONNECTOR_PSQL_USERNAME: connector
      GEUD_CONNECTOR_PSQL_PASSWORD: connector

  node:
    build:
      context: ../../out/node/docker-build/dest
      dockerfile: ../../../../node/Dockerfile
    ports:
      - 127.0.0.1:50053:50053
    depends_on:
      - postgres
      - bitcoind
    environment:
      GEUD_NODE_PSQL_HOST: postgres
      GEUD_NODE_PSQL_DATABASE: node
      GEUD_NODE_PSQL_USERNAME: node
      GEUD_NODE_PSQL_PASSWORD: node
      GEUD_NODE_BITCOIND_HOST: bitcoind
      GEUD_NODE_BITCOIND_PORT: 18333
      GEUD_NODE_BITCOIND_USERNAME: bitcoin
      GEUD_NODE_BITCOIND_PASSWORD: bitcoin
