@startuml

skinparam {
    backgroundColor #EEEBDC
    BorderColor black
    FontColor blackgood good
    ArrowFontName Impact
    ArrowColor #FF6655
    ArrowFontColor #777777
}

title GEUD Indy - Architecutre

cloud "IOHK Cloud" as IOHKCloud {
    [IOHK Connector]
    [IOHK Student Agent]
}

rectangle "Student Phone" as StudentPhone {
    [Student Wallet]
}

rectangle "Issuer Computer" as IssuerComputer {
    [University Wallet]
}

cloud "University Cloud" as UniversityCloud {
    node "Credential Manager"
}

cloud "Indy Cloud" as LedgerCloud {
    node "Node A"
    node "Node B"
    node "Node C"
    [Node A] - [Node B]
    [Node B] - [Node C]
    [Node A] - [Node C] : A cluster of nodes
}

rectangle "Employer Computer" as EmployerComputer {
    [Employer Wallet]
}

IssuerComputer ---- UniversityCloud
LedgerCloud --- UniversityCloud
IOHKCloud ---- StudentPhone
IOHKCloud ---- IssuerComputer
UniversityCloud -- EmployerComputer

@enduml