@startuml
skinparam backgroundColor #EEEBDC

title Indy - Issue credential

actor University
entity "IOHK Agent" as IOHK
actor Student

University -> University : Unlocks cold storage key
University -> IOHK : Send credential offer for student
IOHK -> IOHK : Verifies the university is\n connected to the student
IOHK -> University : Accept credential and send credential request
University -> University : Issue and store the credential
University -> IOHK : Share credential
IOHK -> IOHK : Store the credential
IOHK -> University : Ack
IOHK -> Student : Share credential once it gets online

@enduml