@startuml
title Supply Chain

actor "Government" as Government
actor "Manufacturer" as Manufacturer
database "Blockchain" as Blockchain
actor "Authorized Distributor" as Distributor
actor "Retailer" as Retailer
actor "Consumer" as Consumer
actor "Illegal Retailer" as IllegalSeller

Manufacturer -> Government : Applies for Excise license
Government -> Blockchain : Issues a license to the Manufacturer\n as a verifiable credential
Government -> Manufacturer : Excise license

Manufacturer -> Government : Raises and order for a batch of Products
Government -> Blockchain : Approves the Manufacturer's order\n including a list of Unique\n Identifiers (UID) for each product
Government -> Manufacturer : Sends the UIDs
Manufacturer -> Manufacturer : Delivers the UIDs to the secure Scan Trust Server
Manufacturer -> Manufacturer : Prints custom labels during production\n associating the unique product identifier (PID)
Manufacturer -> Blockchain : Posts associated product and manufacturing data\n Products are put into a “packaged” state

Manufacturer -> Blockchain : The custody state is set to the\n “authorized distributor” and state is set to “shipped”
Manufacturer -> Distributor : Ships the product

Distributor -> Retailer : Ships products
Distributor -> Blockchain : The custody state is set to the\n “retailer name” and state is set to “in store”

Consumer -> Retailer : Picks a product and scan its QR Code
Consumer -> Blockchain : Gets product details
Blockchain -> Consumer : The product is authentic
Consumer -> Retailer : Buys the product
Retailer -> Blockchain : The custody state is set to the\n “Customer” and state is set to “sold”

== When the Manufacturer cheats ==
note right of Manufacturer : Assume the manufacturer attaches the same\n QR Code to several products\n which eventually get to the black market
Consumer -> IllegalSeller : Picks a product and scan its QR Code
Consumer -> Blockchain : Gets product details
Blockchain -> Consumer : The product is not authentic\n the authentic one is with this another Retailer
Consumer -> Retailer : Rejects to buy the product

== When the producs get stolen ==
note over Distributor : The Manufacturer shipped the products\n but they get stolen from the Distributor
Distributor -> Blockchain : Marks the products as stolen
Distributor -> Retailer : Notifies the event
Distributor -> Manufacturer : Notifies the event
Consumer -> IllegalSeller : Picks a product and scan its QR Code
Consumer -> Blockchain : Gets product details
Blockchain -> Consumer : The product was stolen
Consumer -> IllegalSeller : Rejects to buy the product
@enduml
