@startuml
title Bitcoin - Issue credential

participant "ATALA Node" as AtalaNode
actor Issuer
participant IOHK
actor Holder

Issuer -> Issuer : Unlocks cold storage key
Issuer -> Issuer : Find holder's DID and personal details
Issuer -> Issuer : Issue and store the credential
Issuer -> AtalaNode : Store proof-of-existence
AtalaNode -> Issuer : Proof stored
Issuer -> IOHK : Share credential
IOHK -> IOHK : Verifies the issuer is\n connected to the holder
IOHK -> IOHK : Store the credential
IOHK -> Issuer : Ack
IOHK -> Holder : Share credential once it gets online
Holder -> IOHK : Ack
Holder -> Holder : Verify credential validity
Holder -> Holder : Store credential
@enduml