@startuml
title Bitcoin - Holder wallet preparation

actor Holder
participant "Holder Wallet." as HolderWallet

Holder -> HolderWallet : Create wallet
HolderWallet -> HolderWallet : Generate recovery seed
HolderWallet -> Holder : Recovery seed generated
Holder -> Holder : Backups the recovery seed
@enduml