/* eslint-disable */
// source: intdemo_api.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var intdemo_models_pb = require('./intdemo_models_pb.js');
goog.object.extend(proto, intdemo_models_pb);
goog.exportSymbol('proto.io.iohk.prism.intdemo.protos.GetConnectionTokenRequest', null, global);
goog.exportSymbol('proto.io.iohk.prism.intdemo.protos.GetConnectionTokenResponse', null, global);
goog.exportSymbol('proto.io.iohk.prism.intdemo.protos.GetSubjectStatusRequest', null, global);
goog.exportSymbol('proto.io.iohk.prism.intdemo.protos.GetSubjectStatusResponse', null, global);
goog.exportSymbol('proto.io.iohk.prism.intdemo.protos.SetPersonalDataRequest', null, global);
goog.exportSymbol('proto.io.iohk.prism.intdemo.protos.SetPersonalDataResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.iohk.prism.intdemo.protos.GetSubjectStatusRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.iohk.prism.intdemo.protos.GetSubjectStatusRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.io.iohk.prism.intdemo.protos.GetSubjectStatusRequest.displayName = 'proto.io.iohk.prism.intdemo.protos.GetSubjectStatusRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.iohk.prism.intdemo.protos.GetSubjectStatusResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.iohk.prism.intdemo.protos.GetSubjectStatusResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.io.iohk.prism.intdemo.protos.GetSubjectStatusResponse.displayName = 'proto.io.iohk.prism.intdemo.protos.GetSubjectStatusResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.iohk.prism.intdemo.protos.GetConnectionTokenRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.iohk.prism.intdemo.protos.GetConnectionTokenRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.io.iohk.prism.intdemo.protos.GetConnectionTokenRequest.displayName = 'proto.io.iohk.prism.intdemo.protos.GetConnectionTokenRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.iohk.prism.intdemo.protos.GetConnectionTokenResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.iohk.prism.intdemo.protos.GetConnectionTokenResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.io.iohk.prism.intdemo.protos.GetConnectionTokenResponse.displayName = 'proto.io.iohk.prism.intdemo.protos.GetConnectionTokenResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.iohk.prism.intdemo.protos.SetPersonalDataRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.iohk.prism.intdemo.protos.SetPersonalDataRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.io.iohk.prism.intdemo.protos.SetPersonalDataRequest.displayName = 'proto.io.iohk.prism.intdemo.protos.SetPersonalDataRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.iohk.prism.intdemo.protos.SetPersonalDataResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.iohk.prism.intdemo.protos.SetPersonalDataResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.io.iohk.prism.intdemo.protos.SetPersonalDataResponse.displayName = 'proto.io.iohk.prism.intdemo.protos.SetPersonalDataResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.iohk.prism.intdemo.protos.GetSubjectStatusRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.io.iohk.prism.intdemo.protos.GetSubjectStatusRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.iohk.prism.intdemo.protos.GetSubjectStatusRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.prism.intdemo.protos.GetSubjectStatusRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    connectiontoken: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.iohk.prism.intdemo.protos.GetSubjectStatusRequest}
 */
proto.io.iohk.prism.intdemo.protos.GetSubjectStatusRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.iohk.prism.intdemo.protos.GetSubjectStatusRequest;
  return proto.io.iohk.prism.intdemo.protos.GetSubjectStatusRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.iohk.prism.intdemo.protos.GetSubjectStatusRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.iohk.prism.intdemo.protos.GetSubjectStatusRequest}
 */
proto.io.iohk.prism.intdemo.protos.GetSubjectStatusRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setConnectiontoken(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.iohk.prism.intdemo.protos.GetSubjectStatusRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.iohk.prism.intdemo.protos.GetSubjectStatusRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.iohk.prism.intdemo.protos.GetSubjectStatusRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.prism.intdemo.protos.GetSubjectStatusRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getConnectiontoken();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string connectionToken = 1;
 * @return {string}
 */
proto.io.iohk.prism.intdemo.protos.GetSubjectStatusRequest.prototype.getConnectiontoken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.io.iohk.prism.intdemo.protos.GetSubjectStatusRequest} returns this
 */
proto.io.iohk.prism.intdemo.protos.GetSubjectStatusRequest.prototype.setConnectiontoken = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.iohk.prism.intdemo.protos.GetSubjectStatusResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.io.iohk.prism.intdemo.protos.GetSubjectStatusResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.iohk.prism.intdemo.protos.GetSubjectStatusResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.prism.intdemo.protos.GetSubjectStatusResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    subjectstatus: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.iohk.prism.intdemo.protos.GetSubjectStatusResponse}
 */
proto.io.iohk.prism.intdemo.protos.GetSubjectStatusResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.iohk.prism.intdemo.protos.GetSubjectStatusResponse;
  return proto.io.iohk.prism.intdemo.protos.GetSubjectStatusResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.iohk.prism.intdemo.protos.GetSubjectStatusResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.iohk.prism.intdemo.protos.GetSubjectStatusResponse}
 */
proto.io.iohk.prism.intdemo.protos.GetSubjectStatusResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.io.iohk.prism.intdemo.protos.SubjectStatus} */ (reader.readEnum());
      msg.setSubjectstatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.iohk.prism.intdemo.protos.GetSubjectStatusResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.iohk.prism.intdemo.protos.GetSubjectStatusResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.iohk.prism.intdemo.protos.GetSubjectStatusResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.prism.intdemo.protos.GetSubjectStatusResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSubjectstatus();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
};


/**
 * optional SubjectStatus subjectStatus = 1;
 * @return {!proto.io.iohk.prism.intdemo.protos.SubjectStatus}
 */
proto.io.iohk.prism.intdemo.protos.GetSubjectStatusResponse.prototype.getSubjectstatus = function() {
  return /** @type {!proto.io.iohk.prism.intdemo.protos.SubjectStatus} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.io.iohk.prism.intdemo.protos.SubjectStatus} value
 * @return {!proto.io.iohk.prism.intdemo.protos.GetSubjectStatusResponse} returns this
 */
proto.io.iohk.prism.intdemo.protos.GetSubjectStatusResponse.prototype.setSubjectstatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.iohk.prism.intdemo.protos.GetConnectionTokenRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.io.iohk.prism.intdemo.protos.GetConnectionTokenRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.iohk.prism.intdemo.protos.GetConnectionTokenRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.prism.intdemo.protos.GetConnectionTokenRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.iohk.prism.intdemo.protos.GetConnectionTokenRequest}
 */
proto.io.iohk.prism.intdemo.protos.GetConnectionTokenRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.iohk.prism.intdemo.protos.GetConnectionTokenRequest;
  return proto.io.iohk.prism.intdemo.protos.GetConnectionTokenRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.iohk.prism.intdemo.protos.GetConnectionTokenRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.iohk.prism.intdemo.protos.GetConnectionTokenRequest}
 */
proto.io.iohk.prism.intdemo.protos.GetConnectionTokenRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.iohk.prism.intdemo.protos.GetConnectionTokenRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.iohk.prism.intdemo.protos.GetConnectionTokenRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.iohk.prism.intdemo.protos.GetConnectionTokenRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.prism.intdemo.protos.GetConnectionTokenRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.iohk.prism.intdemo.protos.GetConnectionTokenResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.io.iohk.prism.intdemo.protos.GetConnectionTokenResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.iohk.prism.intdemo.protos.GetConnectionTokenResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.prism.intdemo.protos.GetConnectionTokenResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    connectiontoken: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.iohk.prism.intdemo.protos.GetConnectionTokenResponse}
 */
proto.io.iohk.prism.intdemo.protos.GetConnectionTokenResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.iohk.prism.intdemo.protos.GetConnectionTokenResponse;
  return proto.io.iohk.prism.intdemo.protos.GetConnectionTokenResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.iohk.prism.intdemo.protos.GetConnectionTokenResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.iohk.prism.intdemo.protos.GetConnectionTokenResponse}
 */
proto.io.iohk.prism.intdemo.protos.GetConnectionTokenResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setConnectiontoken(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.iohk.prism.intdemo.protos.GetConnectionTokenResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.iohk.prism.intdemo.protos.GetConnectionTokenResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.iohk.prism.intdemo.protos.GetConnectionTokenResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.prism.intdemo.protos.GetConnectionTokenResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getConnectiontoken();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string connectionToken = 1;
 * @return {string}
 */
proto.io.iohk.prism.intdemo.protos.GetConnectionTokenResponse.prototype.getConnectiontoken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.io.iohk.prism.intdemo.protos.GetConnectionTokenResponse} returns this
 */
proto.io.iohk.prism.intdemo.protos.GetConnectionTokenResponse.prototype.setConnectiontoken = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.iohk.prism.intdemo.protos.SetPersonalDataRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.io.iohk.prism.intdemo.protos.SetPersonalDataRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.iohk.prism.intdemo.protos.SetPersonalDataRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.prism.intdemo.protos.SetPersonalDataRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    connectiontoken: jspb.Message.getFieldWithDefault(msg, 1, ""),
    firstname: jspb.Message.getFieldWithDefault(msg, 2, ""),
    dateofbirth: (f = msg.getDateofbirth()) && intdemo_models_pb.Date.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.iohk.prism.intdemo.protos.SetPersonalDataRequest}
 */
proto.io.iohk.prism.intdemo.protos.SetPersonalDataRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.iohk.prism.intdemo.protos.SetPersonalDataRequest;
  return proto.io.iohk.prism.intdemo.protos.SetPersonalDataRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.iohk.prism.intdemo.protos.SetPersonalDataRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.iohk.prism.intdemo.protos.SetPersonalDataRequest}
 */
proto.io.iohk.prism.intdemo.protos.SetPersonalDataRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setConnectiontoken(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setFirstname(value);
      break;
    case 3:
      var value = new intdemo_models_pb.Date;
      reader.readMessage(value,intdemo_models_pb.Date.deserializeBinaryFromReader);
      msg.setDateofbirth(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.iohk.prism.intdemo.protos.SetPersonalDataRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.iohk.prism.intdemo.protos.SetPersonalDataRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.iohk.prism.intdemo.protos.SetPersonalDataRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.prism.intdemo.protos.SetPersonalDataRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getConnectiontoken();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getFirstname();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDateofbirth();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      intdemo_models_pb.Date.serializeBinaryToWriter
    );
  }
};


/**
 * optional string connectionToken = 1;
 * @return {string}
 */
proto.io.iohk.prism.intdemo.protos.SetPersonalDataRequest.prototype.getConnectiontoken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.io.iohk.prism.intdemo.protos.SetPersonalDataRequest} returns this
 */
proto.io.iohk.prism.intdemo.protos.SetPersonalDataRequest.prototype.setConnectiontoken = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string firstName = 2;
 * @return {string}
 */
proto.io.iohk.prism.intdemo.protos.SetPersonalDataRequest.prototype.getFirstname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.io.iohk.prism.intdemo.protos.SetPersonalDataRequest} returns this
 */
proto.io.iohk.prism.intdemo.protos.SetPersonalDataRequest.prototype.setFirstname = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional Date dateOfBirth = 3;
 * @return {?proto.io.iohk.prism.intdemo.protos.Date}
 */
proto.io.iohk.prism.intdemo.protos.SetPersonalDataRequest.prototype.getDateofbirth = function() {
  return /** @type{?proto.io.iohk.prism.intdemo.protos.Date} */ (
    jspb.Message.getWrapperField(this, intdemo_models_pb.Date, 3));
};


/**
 * @param {?proto.io.iohk.prism.intdemo.protos.Date|undefined} value
 * @return {!proto.io.iohk.prism.intdemo.protos.SetPersonalDataRequest} returns this
*/
proto.io.iohk.prism.intdemo.protos.SetPersonalDataRequest.prototype.setDateofbirth = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.io.iohk.prism.intdemo.protos.SetPersonalDataRequest} returns this
 */
proto.io.iohk.prism.intdemo.protos.SetPersonalDataRequest.prototype.clearDateofbirth = function() {
  return this.setDateofbirth(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.io.iohk.prism.intdemo.protos.SetPersonalDataRequest.prototype.hasDateofbirth = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.iohk.prism.intdemo.protos.SetPersonalDataResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.io.iohk.prism.intdemo.protos.SetPersonalDataResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.iohk.prism.intdemo.protos.SetPersonalDataResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.prism.intdemo.protos.SetPersonalDataResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.iohk.prism.intdemo.protos.SetPersonalDataResponse}
 */
proto.io.iohk.prism.intdemo.protos.SetPersonalDataResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.iohk.prism.intdemo.protos.SetPersonalDataResponse;
  return proto.io.iohk.prism.intdemo.protos.SetPersonalDataResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.iohk.prism.intdemo.protos.SetPersonalDataResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.iohk.prism.intdemo.protos.SetPersonalDataResponse}
 */
proto.io.iohk.prism.intdemo.protos.SetPersonalDataResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.iohk.prism.intdemo.protos.SetPersonalDataResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.iohk.prism.intdemo.protos.SetPersonalDataResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.iohk.prism.intdemo.protos.SetPersonalDataResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.prism.intdemo.protos.SetPersonalDataResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};


goog.object.extend(exports, proto.io.iohk.prism.intdemo.protos);
