load("//scala:rules.bzl", "scala_library", "scala_test")

scala_library(
    name = "test",
    deps = [ "//3rdparty/jvm/org/scalacheck:scalacheck",
             "//3rdparty/jvm/org/scalatest:scalatest",
             "//3rdparty/jvm/com/typesafe:config",
             "//3rdparty/jvm/com/typesafe/akka:akka_actor" ],
)

