load("//scala:rules.bzl", "scala_library", "scala_test")

scala_library(
    name = "test",
    deps = [
        "//3rdparty/jvm/com/typesafe:config",
        "//3rdparty/jvm/com/typesafe/akka:akka_actor",
        "//3rdparty/jvm/com/typesafe/akka:akka_actor_typed",
        "//3rdparty/jvm/com/typesafe/akka:akka_slf4j",
        "//3rdparty/jvm/com/typesafe/akka:akka_testkit",
        "//3rdparty/jvm/com/typesafe/akka:akka_testkit_typed",
        "//3rdparty/jvm/org/scalacheck",
        "//3rdparty/jvm/org/scalatest",
    ],
)
