load("//scala:rules.bzl", "scala_library", "scala_test")

scala_library(
    name = "testlib",
    deps = [ "//main/io/iohk/cef/consensus" ],
    external = [
      "org.mockito:mockito-core",
      "org.scalatest:scalatest%",
    ],
)
