load("//scala:rules.bzl", "scala_library", "scala_test")

scala_library(
    name = "testlib",
    deps = [ "//main/io/iohk/cef/consensus",
             "@codecs//src/io/iohk/codecs",
             "//3rdparty/jvm/org/scalatest",
             "//3rdparty/jvm/org/mockito:mockito_core", ],
)