@startuml
title Share credential

actor Issuer
participant "Management Console" as ManagementConsole
participant "Prism Browser Wallet" as BrowserWallet
participant "IOHK Server API" as ServerAPI
participant "Prism Mobile Wallet" as MobileWallet

group Share the credential to the group
    Issuer -> ManagementConsole : Share credential group
    ManagementConsole -> BrowserWallet : Encrypt credentials group
    BrowserWallet -> Issuer : Asks to confirm the operation
    Issuer -> BrowserWallet : Confirm
    BrowserWallet -> BrowserWallet : Encrypt credentials
    BrowserWallet -> ManagementConsole : Encrypted credentials
    ManagementConsole -> ServerAPI : Send encrypted credentials
    ServerAPI -> MobileWallet : Send credential
    ServerAPI -> ManagementConsole : Credentials sent
    ManagementConsole -> Issuer : Credentials sent
end
@enduml