
@startuml
title Share credential to be verified

participant "IOHK Server API" as ServerAPI
participant "Prism Mobile Wallet" as MobileWallet
actor Holder

group Share the credential to the verifier entity
    Holder -> MobileWallet : View credential to share
    MobileWallet -> Holder : Credential
    Holder -> MobileWallet : Share
    MobileWallet -> Holder : Ask who to share with
    Holder -> MobileWallet : Choose recipient
    MobileWallet -> MobileWallet : Encrypt credential
    MobileWallet -> ServerAPI : Share encrypted credential
    ServerAPI -> MobileWallet : Credential shared
    MobileWallet -> Holder : Credential shared
end
@enduml
