
@startuml
title Verify a credential

actor Verifier
participant "Management Console" as ManagementConsole
participant "Prism Browser Wallet" as BrowserWallet
participant "IOHK Server API" as ServerAPI

group Get a credential shared from a mobile wallet
    Verifier -> ManagementConsole : Choose a person
    ManagementConsole -> Verifier : Ask to choose the credential
    Verifier -> ManagementConsole : Choose credential
    ManagementConsole -> ServerAPI : Get credential
    ServerAPI -> ManagementConsole : Credential
end

group Verify a credential
    ManagementConsole -> BrowserWallet : Verify credential
    BrowserWallet -> BrowserWallet : Decrypt credential
    BrowserWallet -> ServerAPI : Get credential state from Cardano
    ServerAPI -> BrowserWallet : Credential state
    BrowserWallet -> ServerAPI : Get issuer DID from Cardano
    ServerAPI -> BrowserWallet : DID Document
    BrowserWallet -> BrowserWallet : Verify credential state isn't revoked/expired
    BrowserWallet -> BrowserWallet : Verify issuance date
    BrowserWallet -> BrowserWallet : Verify issuer key was valid when issuing the credential
    BrowserWallet -> BrowserWallet : Verify issuer key signed the credential
    BrowserWallet -> ManagementConsole : Verification result
    ManagementConsole -> Verifier : Verification result
end
@enduml
