@startuml
!include ../common/C4_header.puml

Title <b>Atala PRISM</b>

cloud "Cardano Mainnet" as Cardano_Mainnet {
  System_Boundary(Cardano_Boundary, "Cardano") {
    Container(Cloud_Cardano_Node, "Cardano Node", "Cardano", "Blockchain")
  }
}

System_Boundary(PRISM, "PRISM") {
    Container_Boundary(Node_Boundary, "Node Service") {
      ContainerDb(PRISM_Node_Db, "PRISM Node Db", "PRISM", "Slayer Indexing DB")
      Container(PRISM_Node, "PRISM Node", "PRISM", "Slayer Protocol API")

      Container(Cardano_Wallet_Backend, "Cardano Wallet Backend", "Cardano", "Write Path")
      ContainerDb(Cardano_Db_Sync, "Cardano DB Sync", "Cardano", "Read Path")

      Container(Cardano_Node, "Cardano Node", "Cardano", "Blockchain")

      Cardano_Wallet_Backend -down-> Cardano_Node
      Cardano_Db_Sync        -down-> Cardano_Node
    }

    PRISM_Node -right-> PRISM_Node_Db
    PRISM_Node -down->  Cardano_Wallet_Backend
    PRISM_Node -down->  Cardano_Db_Sync
    Cardano_Node -right-> Cardano_Mainnet

    Container_Boundary(Vault_Boundary, "Vault Service") {
      Container(Vault, "Vault", "PRISM", "Vault API")
      Container(Vault_Db, "Vault Db", "PRISM", "Vault Storage")

      Vault -down-> Vault_Db
    }

    Container_Boundary(Connector_Boundary, "Connector Service") {
      Container(Connector, "Connector", "PRISM", "P2P Channel API")
      ContainerDb(Connector_Db, "Connector Db", "PRISM", "P2P Mailbox")

      Connector -down-> Connector_Db
    }

    

    Connector -right-> PRISM_Node

    Container_Boundary(MC, "Management Console [MC]") {
      Container(MC_Frontend, "MC Frontend", "PRISM", "MC App, Browser Wallet")
      Container(MC_Backend, "MC Backend", "PRISM", "MC API")
      ContainerDb(MC_Db, "MC Db", "PRISM", "Credentials Store")

      MC_Backend -up-> MC_Db
      MC_Backend -down-> Connector
      MC_Frontend -left-> MC_Backend
    }

    Container(Mobile_Wallet, "Mobile Wallet", "PRISM", "Android, iOS")
    Mobile_Wallet ---> Connector
    Mobile_Wallet ---> PRISM_Node
    Mobile_Wallet -up-> Vault

    Container(Browser_Wallet, "Browser Wallet", "PRISM", "Chrome, Firefox")
    MC_Frontend -right-> Browser_Wallet
    Browser_Wallet ---> PRISM_Node
    Browser_Wallet -> Connector
}
@enduml