load("//scala:rules.bzl", "scala_library", "scala_test")

scala_library(
  name = "state",
  deps = [
    "//atala/logging:logging",
    "//atala/helpers/monixhelpers:monixhelpers",
  ],
  external = [
    "io.monix:monix%"
  ],
)

