all:
	pdflatex gsac.tex
	bibtex gsac
	pdflatex gsac.tex
	pdflatex gsac.tex
	pdflatex uas.tex
	bibtex uas
	pdflatex uas.tex
	pdflatex uas.tex

gsac:
	pdflatex gsac.tex
	bibtex gsac
	pdflatex gsac.tex
	pdflatex gsac.tex

uas:
	pdflatex uas.tex
	bibtex uas
	pdflatex uas.tex
	pdflatex uas.tex

clean:
	rm *~ *.aux *.log *.blg *.bbl *.out
