/* eslint-disable */
// source: console_models.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.io.iohk.atala.prism.protos.Contact', null, global);
goog.exportSymbol('proto.io.iohk.atala.prism.protos.ContactConnectionStatus', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.iohk.atala.prism.protos.Contact = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.iohk.atala.prism.protos.Contact, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.io.iohk.atala.prism.protos.Contact.displayName = 'proto.io.iohk.atala.prism.protos.Contact';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.iohk.atala.prism.protos.Contact.prototype.toObject = function(opt_includeInstance) {
  return proto.io.iohk.atala.prism.protos.Contact.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.iohk.atala.prism.protos.Contact} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.atala.prism.protos.Contact.toObject = function(includeInstance, msg) {
  var f, obj = {
    contactid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    externalid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    jsondata: jspb.Message.getFieldWithDefault(msg, 3, ""),
    connectionstatus: jspb.Message.getFieldWithDefault(msg, 4, 0),
    connectiontoken: jspb.Message.getFieldWithDefault(msg, 5, ""),
    connectionid: jspb.Message.getFieldWithDefault(msg, 6, ""),
    createdat: jspb.Message.getFieldWithDefault(msg, 7, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.iohk.atala.prism.protos.Contact}
 */
proto.io.iohk.atala.prism.protos.Contact.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.iohk.atala.prism.protos.Contact;
  return proto.io.iohk.atala.prism.protos.Contact.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.iohk.atala.prism.protos.Contact} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.iohk.atala.prism.protos.Contact}
 */
proto.io.iohk.atala.prism.protos.Contact.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setContactid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setExternalid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setJsondata(value);
      break;
    case 4:
      var value = /** @type {!proto.io.iohk.atala.prism.protos.ContactConnectionStatus} */ (reader.readEnum());
      msg.setConnectionstatus(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setConnectiontoken(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setConnectionid(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCreatedat(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.iohk.atala.prism.protos.Contact.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.iohk.atala.prism.protos.Contact.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.iohk.atala.prism.protos.Contact} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.atala.prism.protos.Contact.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getContactid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getExternalid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getJsondata();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getConnectionstatus();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getConnectiontoken();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getConnectionid();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getCreatedat();
  if (f !== 0) {
    writer.writeInt64(
      7,
      f
    );
  }
};


/**
 * optional string contactId = 1;
 * @return {string}
 */
proto.io.iohk.atala.prism.protos.Contact.prototype.getContactid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.io.iohk.atala.prism.protos.Contact} returns this
 */
proto.io.iohk.atala.prism.protos.Contact.prototype.setContactid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string externalId = 2;
 * @return {string}
 */
proto.io.iohk.atala.prism.protos.Contact.prototype.getExternalid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.io.iohk.atala.prism.protos.Contact} returns this
 */
proto.io.iohk.atala.prism.protos.Contact.prototype.setExternalid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string jsonData = 3;
 * @return {string}
 */
proto.io.iohk.atala.prism.protos.Contact.prototype.getJsondata = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.io.iohk.atala.prism.protos.Contact} returns this
 */
proto.io.iohk.atala.prism.protos.Contact.prototype.setJsondata = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional ContactConnectionStatus connectionStatus = 4;
 * @return {!proto.io.iohk.atala.prism.protos.ContactConnectionStatus}
 */
proto.io.iohk.atala.prism.protos.Contact.prototype.getConnectionstatus = function() {
  return /** @type {!proto.io.iohk.atala.prism.protos.ContactConnectionStatus} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.io.iohk.atala.prism.protos.ContactConnectionStatus} value
 * @return {!proto.io.iohk.atala.prism.protos.Contact} returns this
 */
proto.io.iohk.atala.prism.protos.Contact.prototype.setConnectionstatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional string connectionToken = 5;
 * @return {string}
 */
proto.io.iohk.atala.prism.protos.Contact.prototype.getConnectiontoken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.io.iohk.atala.prism.protos.Contact} returns this
 */
proto.io.iohk.atala.prism.protos.Contact.prototype.setConnectiontoken = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string connectionId = 6;
 * @return {string}
 */
proto.io.iohk.atala.prism.protos.Contact.prototype.getConnectionid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.io.iohk.atala.prism.protos.Contact} returns this
 */
proto.io.iohk.atala.prism.protos.Contact.prototype.setConnectionid = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional int64 createdAt = 7;
 * @return {number}
 */
proto.io.iohk.atala.prism.protos.Contact.prototype.getCreatedat = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.io.iohk.atala.prism.protos.Contact} returns this
 */
proto.io.iohk.atala.prism.protos.Contact.prototype.setCreatedat = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * @enum {number}
 */
proto.io.iohk.atala.prism.protos.ContactConnectionStatus = {
  STATUS_MISSING: 0,
  INVITATION_MISSING: 1,
  CONNECTION_MISSING: 2,
  CONNECTION_ACCEPTED: 3,
  CONNECTION_REVOKED: 4
};

goog.object.extend(exports, proto.io.iohk.atala.prism.protos);
