/* eslint-disable */
// source: credential_models.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var common_models_pb = require('./common_models_pb.js');
goog.object.extend(proto, common_models_pb);
goog.exportSymbol('proto.io.iohk.prism.protos.AlphaCredential', null, global);
goog.exportSymbol('proto.io.iohk.prism.protos.AtalaMessage', null, global);
goog.exportSymbol('proto.io.iohk.prism.protos.AtalaMessage.MessageCase', null, global);
goog.exportSymbol('proto.io.iohk.prism.protos.Credential', null, global);
goog.exportSymbol('proto.io.iohk.prism.protos.HolderSentCredential', null, global);
goog.exportSymbol('proto.io.iohk.prism.protos.IdDocumentType', null, global);
goog.exportSymbol('proto.io.iohk.prism.protos.IssuerData', null, global);
goog.exportSymbol('proto.io.iohk.prism.protos.IssuerSentCredential', null, global);
goog.exportSymbol('proto.io.iohk.prism.protos.IssuerSentCredential.ValueCase', null, global);
goog.exportSymbol('proto.io.iohk.prism.protos.IssuerType', null, global);
goog.exportSymbol('proto.io.iohk.prism.protos.PersonalId', null, global);
goog.exportSymbol('proto.io.iohk.prism.protos.ProofRequest', null, global);
goog.exportSymbol('proto.io.iohk.prism.protos.Signer', null, global);
goog.exportSymbol('proto.io.iohk.prism.protos.SubjectData', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.iohk.prism.protos.AlphaCredential = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.io.iohk.prism.protos.AlphaCredential.repeatedFields_, null);
};
goog.inherits(proto.io.iohk.prism.protos.AlphaCredential, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.io.iohk.prism.protos.AlphaCredential.displayName = 'proto.io.iohk.prism.protos.AlphaCredential';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.iohk.prism.protos.IssuerData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.iohk.prism.protos.IssuerData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.io.iohk.prism.protos.IssuerData.displayName = 'proto.io.iohk.prism.protos.IssuerData';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.iohk.prism.protos.Signer = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.io.iohk.prism.protos.Signer.repeatedFields_, null);
};
goog.inherits(proto.io.iohk.prism.protos.Signer, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.io.iohk.prism.protos.Signer.displayName = 'proto.io.iohk.prism.protos.Signer';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.iohk.prism.protos.SubjectData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.io.iohk.prism.protos.SubjectData.repeatedFields_, null);
};
goog.inherits(proto.io.iohk.prism.protos.SubjectData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.io.iohk.prism.protos.SubjectData.displayName = 'proto.io.iohk.prism.protos.SubjectData';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.iohk.prism.protos.PersonalId = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.iohk.prism.protos.PersonalId, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.io.iohk.prism.protos.PersonalId.displayName = 'proto.io.iohk.prism.protos.PersonalId';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.iohk.prism.protos.IssuerSentCredential = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.io.iohk.prism.protos.IssuerSentCredential.oneofGroups_);
};
goog.inherits(proto.io.iohk.prism.protos.IssuerSentCredential, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.io.iohk.prism.protos.IssuerSentCredential.displayName = 'proto.io.iohk.prism.protos.IssuerSentCredential';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.iohk.prism.protos.Credential = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.iohk.prism.protos.Credential, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.io.iohk.prism.protos.Credential.displayName = 'proto.io.iohk.prism.protos.Credential';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.iohk.prism.protos.HolderSentCredential = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.iohk.prism.protos.HolderSentCredential, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.io.iohk.prism.protos.HolderSentCredential.displayName = 'proto.io.iohk.prism.protos.HolderSentCredential';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.iohk.prism.protos.ProofRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.iohk.prism.protos.ProofRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.io.iohk.prism.protos.ProofRequest.displayName = 'proto.io.iohk.prism.protos.ProofRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.iohk.prism.protos.AtalaMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.io.iohk.prism.protos.AtalaMessage.oneofGroups_);
};
goog.inherits(proto.io.iohk.prism.protos.AtalaMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.io.iohk.prism.protos.AtalaMessage.displayName = 'proto.io.iohk.prism.protos.AtalaMessage';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.io.iohk.prism.protos.AlphaCredential.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.iohk.prism.protos.AlphaCredential.prototype.toObject = function(opt_includeInstance) {
  return proto.io.iohk.prism.protos.AlphaCredential.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.iohk.prism.protos.AlphaCredential} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.prism.protos.AlphaCredential.toObject = function(includeInstance, msg) {
  var f, obj = {
    issuertype: (f = msg.getIssuertype()) && proto.io.iohk.prism.protos.IssuerData.toObject(includeInstance, f),
    subjectdata: (f = msg.getSubjectdata()) && proto.io.iohk.prism.protos.SubjectData.toObject(includeInstance, f),
    grantingdecision: jspb.Message.getFieldWithDefault(msg, 3, ""),
    signingauthoritiesList: jspb.Message.toObjectList(msg.getSigningauthoritiesList(),
    proto.io.iohk.prism.protos.Signer.toObject, includeInstance),
    degreeawarded: jspb.Message.getFieldWithDefault(msg, 5, ""),
    additionalspeciality: jspb.Message.getFieldWithDefault(msg, 6, ""),
    issuedon: (f = msg.getIssuedon()) && common_models_pb.Date.toObject(includeInstance, f),
    issuenumber: jspb.Message.getFieldWithDefault(msg, 8, ""),
    registrationnumber: jspb.Message.getFieldWithDefault(msg, 9, ""),
    decisionnumber: jspb.Message.getFieldWithDefault(msg, 10, ""),
    yearcompletedbystudent: jspb.Message.getFieldWithDefault(msg, 15, ""),
    description: jspb.Message.getFieldWithDefault(msg, 16, ""),
    expireson: (f = msg.getExpireson()) && common_models_pb.Date.toObject(includeInstance, f),
    admissiondate: (f = msg.getAdmissiondate()) && common_models_pb.Date.toObject(includeInstance, f),
    graduationdate: (f = msg.getGraduationdate()) && common_models_pb.Date.toObject(includeInstance, f),
    attainmentdate: (f = msg.getAttainmentdate()) && common_models_pb.Date.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.iohk.prism.protos.AlphaCredential}
 */
proto.io.iohk.prism.protos.AlphaCredential.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.iohk.prism.protos.AlphaCredential;
  return proto.io.iohk.prism.protos.AlphaCredential.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.iohk.prism.protos.AlphaCredential} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.iohk.prism.protos.AlphaCredential}
 */
proto.io.iohk.prism.protos.AlphaCredential.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.io.iohk.prism.protos.IssuerData;
      reader.readMessage(value,proto.io.iohk.prism.protos.IssuerData.deserializeBinaryFromReader);
      msg.setIssuertype(value);
      break;
    case 2:
      var value = new proto.io.iohk.prism.protos.SubjectData;
      reader.readMessage(value,proto.io.iohk.prism.protos.SubjectData.deserializeBinaryFromReader);
      msg.setSubjectdata(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setGrantingdecision(value);
      break;
    case 4:
      var value = new proto.io.iohk.prism.protos.Signer;
      reader.readMessage(value,proto.io.iohk.prism.protos.Signer.deserializeBinaryFromReader);
      msg.addSigningauthorities(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setDegreeawarded(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setAdditionalspeciality(value);
      break;
    case 7:
      var value = new common_models_pb.Date;
      reader.readMessage(value,common_models_pb.Date.deserializeBinaryFromReader);
      msg.setIssuedon(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setIssuenumber(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setRegistrationnumber(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setDecisionnumber(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.setYearcompletedbystudent(value);
      break;
    case 16:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 17:
      var value = new common_models_pb.Date;
      reader.readMessage(value,common_models_pb.Date.deserializeBinaryFromReader);
      msg.setExpireson(value);
      break;
    case 18:
      var value = new common_models_pb.Date;
      reader.readMessage(value,common_models_pb.Date.deserializeBinaryFromReader);
      msg.setAdmissiondate(value);
      break;
    case 19:
      var value = new common_models_pb.Date;
      reader.readMessage(value,common_models_pb.Date.deserializeBinaryFromReader);
      msg.setGraduationdate(value);
      break;
    case 20:
      var value = new common_models_pb.Date;
      reader.readMessage(value,common_models_pb.Date.deserializeBinaryFromReader);
      msg.setAttainmentdate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.iohk.prism.protos.AlphaCredential.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.iohk.prism.protos.AlphaCredential.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.iohk.prism.protos.AlphaCredential} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.prism.protos.AlphaCredential.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIssuertype();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.io.iohk.prism.protos.IssuerData.serializeBinaryToWriter
    );
  }
  f = message.getSubjectdata();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.io.iohk.prism.protos.SubjectData.serializeBinaryToWriter
    );
  }
  f = message.getGrantingdecision();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getSigningauthoritiesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.io.iohk.prism.protos.Signer.serializeBinaryToWriter
    );
  }
  f = message.getDegreeawarded();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getAdditionalspeciality();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getIssuedon();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      common_models_pb.Date.serializeBinaryToWriter
    );
  }
  f = message.getIssuenumber();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getRegistrationnumber();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getDecisionnumber();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getYearcompletedbystudent();
  if (f.length > 0) {
    writer.writeString(
      15,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      16,
      f
    );
  }
  f = message.getExpireson();
  if (f != null) {
    writer.writeMessage(
      17,
      f,
      common_models_pb.Date.serializeBinaryToWriter
    );
  }
  f = message.getAdmissiondate();
  if (f != null) {
    writer.writeMessage(
      18,
      f,
      common_models_pb.Date.serializeBinaryToWriter
    );
  }
  f = message.getGraduationdate();
  if (f != null) {
    writer.writeMessage(
      19,
      f,
      common_models_pb.Date.serializeBinaryToWriter
    );
  }
  f = message.getAttainmentdate();
  if (f != null) {
    writer.writeMessage(
      20,
      f,
      common_models_pb.Date.serializeBinaryToWriter
    );
  }
};


/**
 * optional IssuerData issuerType = 1;
 * @return {?proto.io.iohk.prism.protos.IssuerData}
 */
proto.io.iohk.prism.protos.AlphaCredential.prototype.getIssuertype = function() {
  return /** @type{?proto.io.iohk.prism.protos.IssuerData} */ (
    jspb.Message.getWrapperField(this, proto.io.iohk.prism.protos.IssuerData, 1));
};


/** @param {?proto.io.iohk.prism.protos.IssuerData|undefined} value */
proto.io.iohk.prism.protos.AlphaCredential.prototype.setIssuertype = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.io.iohk.prism.protos.AlphaCredential.prototype.clearIssuertype = function() {
  this.setIssuertype(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.io.iohk.prism.protos.AlphaCredential.prototype.hasIssuertype = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional SubjectData subjectData = 2;
 * @return {?proto.io.iohk.prism.protos.SubjectData}
 */
proto.io.iohk.prism.protos.AlphaCredential.prototype.getSubjectdata = function() {
  return /** @type{?proto.io.iohk.prism.protos.SubjectData} */ (
    jspb.Message.getWrapperField(this, proto.io.iohk.prism.protos.SubjectData, 2));
};


/** @param {?proto.io.iohk.prism.protos.SubjectData|undefined} value */
proto.io.iohk.prism.protos.AlphaCredential.prototype.setSubjectdata = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.io.iohk.prism.protos.AlphaCredential.prototype.clearSubjectdata = function() {
  this.setSubjectdata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.io.iohk.prism.protos.AlphaCredential.prototype.hasSubjectdata = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string grantingDecision = 3;
 * @return {string}
 */
proto.io.iohk.prism.protos.AlphaCredential.prototype.getGrantingdecision = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.io.iohk.prism.protos.AlphaCredential.prototype.setGrantingdecision = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * repeated Signer signingAuthorities = 4;
 * @return {!Array<!proto.io.iohk.prism.protos.Signer>}
 */
proto.io.iohk.prism.protos.AlphaCredential.prototype.getSigningauthoritiesList = function() {
  return /** @type{!Array<!proto.io.iohk.prism.protos.Signer>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.io.iohk.prism.protos.Signer, 4));
};


/** @param {!Array<!proto.io.iohk.prism.protos.Signer>} value */
proto.io.iohk.prism.protos.AlphaCredential.prototype.setSigningauthoritiesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.io.iohk.prism.protos.Signer=} opt_value
 * @param {number=} opt_index
 * @return {!proto.io.iohk.prism.protos.Signer}
 */
proto.io.iohk.prism.protos.AlphaCredential.prototype.addSigningauthorities = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.io.iohk.prism.protos.Signer, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.io.iohk.prism.protos.AlphaCredential.prototype.clearSigningauthoritiesList = function() {
  this.setSigningauthoritiesList([]);
};


/**
 * optional string degreeAwarded = 5;
 * @return {string}
 */
proto.io.iohk.prism.protos.AlphaCredential.prototype.getDegreeawarded = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.io.iohk.prism.protos.AlphaCredential.prototype.setDegreeawarded = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string additionalSpeciality = 6;
 * @return {string}
 */
proto.io.iohk.prism.protos.AlphaCredential.prototype.getAdditionalspeciality = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.io.iohk.prism.protos.AlphaCredential.prototype.setAdditionalspeciality = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional Date issuedOn = 7;
 * @return {?proto.io.iohk.prism.protos.Date}
 */
proto.io.iohk.prism.protos.AlphaCredential.prototype.getIssuedon = function() {
  return /** @type{?proto.io.iohk.prism.protos.Date} */ (
    jspb.Message.getWrapperField(this, common_models_pb.Date, 7));
};


/** @param {?proto.io.iohk.prism.protos.Date|undefined} value */
proto.io.iohk.prism.protos.AlphaCredential.prototype.setIssuedon = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.io.iohk.prism.protos.AlphaCredential.prototype.clearIssuedon = function() {
  this.setIssuedon(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.io.iohk.prism.protos.AlphaCredential.prototype.hasIssuedon = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional string issueNumber = 8;
 * @return {string}
 */
proto.io.iohk.prism.protos.AlphaCredential.prototype.getIssuenumber = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/** @param {string} value */
proto.io.iohk.prism.protos.AlphaCredential.prototype.setIssuenumber = function(value) {
  jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string registrationNumber = 9;
 * @return {string}
 */
proto.io.iohk.prism.protos.AlphaCredential.prototype.getRegistrationnumber = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/** @param {string} value */
proto.io.iohk.prism.protos.AlphaCredential.prototype.setRegistrationnumber = function(value) {
  jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string decisionNumber = 10;
 * @return {string}
 */
proto.io.iohk.prism.protos.AlphaCredential.prototype.getDecisionnumber = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/** @param {string} value */
proto.io.iohk.prism.protos.AlphaCredential.prototype.setDecisionnumber = function(value) {
  jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string yearCompletedByStudent = 15;
 * @return {string}
 */
proto.io.iohk.prism.protos.AlphaCredential.prototype.getYearcompletedbystudent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
};


/** @param {string} value */
proto.io.iohk.prism.protos.AlphaCredential.prototype.setYearcompletedbystudent = function(value) {
  jspb.Message.setProto3StringField(this, 15, value);
};


/**
 * optional string description = 16;
 * @return {string}
 */
proto.io.iohk.prism.protos.AlphaCredential.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 16, ""));
};


/** @param {string} value */
proto.io.iohk.prism.protos.AlphaCredential.prototype.setDescription = function(value) {
  jspb.Message.setProto3StringField(this, 16, value);
};


/**
 * optional Date expiresOn = 17;
 * @return {?proto.io.iohk.prism.protos.Date}
 */
proto.io.iohk.prism.protos.AlphaCredential.prototype.getExpireson = function() {
  return /** @type{?proto.io.iohk.prism.protos.Date} */ (
    jspb.Message.getWrapperField(this, common_models_pb.Date, 17));
};


/** @param {?proto.io.iohk.prism.protos.Date|undefined} value */
proto.io.iohk.prism.protos.AlphaCredential.prototype.setExpireson = function(value) {
  jspb.Message.setWrapperField(this, 17, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.io.iohk.prism.protos.AlphaCredential.prototype.clearExpireson = function() {
  this.setExpireson(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.io.iohk.prism.protos.AlphaCredential.prototype.hasExpireson = function() {
  return jspb.Message.getField(this, 17) != null;
};


/**
 * optional Date admissionDate = 18;
 * @return {?proto.io.iohk.prism.protos.Date}
 */
proto.io.iohk.prism.protos.AlphaCredential.prototype.getAdmissiondate = function() {
  return /** @type{?proto.io.iohk.prism.protos.Date} */ (
    jspb.Message.getWrapperField(this, common_models_pb.Date, 18));
};


/** @param {?proto.io.iohk.prism.protos.Date|undefined} value */
proto.io.iohk.prism.protos.AlphaCredential.prototype.setAdmissiondate = function(value) {
  jspb.Message.setWrapperField(this, 18, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.io.iohk.prism.protos.AlphaCredential.prototype.clearAdmissiondate = function() {
  this.setAdmissiondate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.io.iohk.prism.protos.AlphaCredential.prototype.hasAdmissiondate = function() {
  return jspb.Message.getField(this, 18) != null;
};


/**
 * optional Date graduationDate = 19;
 * @return {?proto.io.iohk.prism.protos.Date}
 */
proto.io.iohk.prism.protos.AlphaCredential.prototype.getGraduationdate = function() {
  return /** @type{?proto.io.iohk.prism.protos.Date} */ (
    jspb.Message.getWrapperField(this, common_models_pb.Date, 19));
};


/** @param {?proto.io.iohk.prism.protos.Date|undefined} value */
proto.io.iohk.prism.protos.AlphaCredential.prototype.setGraduationdate = function(value) {
  jspb.Message.setWrapperField(this, 19, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.io.iohk.prism.protos.AlphaCredential.prototype.clearGraduationdate = function() {
  this.setGraduationdate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.io.iohk.prism.protos.AlphaCredential.prototype.hasGraduationdate = function() {
  return jspb.Message.getField(this, 19) != null;
};


/**
 * optional Date attainmentDate = 20;
 * @return {?proto.io.iohk.prism.protos.Date}
 */
proto.io.iohk.prism.protos.AlphaCredential.prototype.getAttainmentdate = function() {
  return /** @type{?proto.io.iohk.prism.protos.Date} */ (
    jspb.Message.getWrapperField(this, common_models_pb.Date, 20));
};


/** @param {?proto.io.iohk.prism.protos.Date|undefined} value */
proto.io.iohk.prism.protos.AlphaCredential.prototype.setAttainmentdate = function(value) {
  jspb.Message.setWrapperField(this, 20, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.io.iohk.prism.protos.AlphaCredential.prototype.clearAttainmentdate = function() {
  this.setAttainmentdate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.io.iohk.prism.protos.AlphaCredential.prototype.hasAttainmentdate = function() {
  return jspb.Message.getField(this, 20) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.iohk.prism.protos.IssuerData.prototype.toObject = function(opt_includeInstance) {
  return proto.io.iohk.prism.protos.IssuerData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.iohk.prism.protos.IssuerData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.prism.protos.IssuerData.toObject = function(includeInstance, msg) {
  var f, obj = {
    issuerlegalname: jspb.Message.getFieldWithDefault(msg, 1, ""),
    academicauthority: jspb.Message.getFieldWithDefault(msg, 2, ""),
    issuertype: jspb.Message.getFieldWithDefault(msg, 3, 0),
    did: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.iohk.prism.protos.IssuerData}
 */
proto.io.iohk.prism.protos.IssuerData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.iohk.prism.protos.IssuerData;
  return proto.io.iohk.prism.protos.IssuerData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.iohk.prism.protos.IssuerData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.iohk.prism.protos.IssuerData}
 */
proto.io.iohk.prism.protos.IssuerData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setIssuerlegalname(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAcademicauthority(value);
      break;
    case 3:
      var value = /** @type {!proto.io.iohk.prism.protos.IssuerType} */ (reader.readEnum());
      msg.setIssuertype(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setDid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.iohk.prism.protos.IssuerData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.iohk.prism.protos.IssuerData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.iohk.prism.protos.IssuerData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.prism.protos.IssuerData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIssuerlegalname();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAcademicauthority();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getIssuertype();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getDid();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional string issuerLegalName = 1;
 * @return {string}
 */
proto.io.iohk.prism.protos.IssuerData.prototype.getIssuerlegalname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.io.iohk.prism.protos.IssuerData.prototype.setIssuerlegalname = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string academicAuthority = 2;
 * @return {string}
 */
proto.io.iohk.prism.protos.IssuerData.prototype.getAcademicauthority = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.io.iohk.prism.protos.IssuerData.prototype.setAcademicauthority = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional IssuerType issuerType = 3;
 * @return {!proto.io.iohk.prism.protos.IssuerType}
 */
proto.io.iohk.prism.protos.IssuerData.prototype.getIssuertype = function() {
  return /** @type {!proto.io.iohk.prism.protos.IssuerType} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {!proto.io.iohk.prism.protos.IssuerType} value */
proto.io.iohk.prism.protos.IssuerData.prototype.setIssuertype = function(value) {
  jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional string did = 4;
 * @return {string}
 */
proto.io.iohk.prism.protos.IssuerData.prototype.getDid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.io.iohk.prism.protos.IssuerData.prototype.setDid = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.io.iohk.prism.protos.Signer.repeatedFields_ = [1,2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.iohk.prism.protos.Signer.prototype.toObject = function(opt_includeInstance) {
  return proto.io.iohk.prism.protos.Signer.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.iohk.prism.protos.Signer} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.prism.protos.Signer.toObject = function(includeInstance, msg) {
  var f, obj = {
    namesList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f,
    surnamesList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f,
    role: jspb.Message.getFieldWithDefault(msg, 3, ""),
    did: jspb.Message.getFieldWithDefault(msg, 4, ""),
    title: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.iohk.prism.protos.Signer}
 */
proto.io.iohk.prism.protos.Signer.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.iohk.prism.protos.Signer;
  return proto.io.iohk.prism.protos.Signer.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.iohk.prism.protos.Signer} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.iohk.prism.protos.Signer}
 */
proto.io.iohk.prism.protos.Signer.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addNames(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addSurnames(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setRole(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setDid(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.iohk.prism.protos.Signer.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.iohk.prism.protos.Signer.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.iohk.prism.protos.Signer} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.prism.protos.Signer.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNamesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
  f = message.getSurnamesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getRole();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getDid();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * repeated string names = 1;
 * @return {!Array<string>}
 */
proto.io.iohk.prism.protos.Signer.prototype.getNamesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/** @param {!Array<string>} value */
proto.io.iohk.prism.protos.Signer.prototype.setNamesList = function(value) {
  jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.io.iohk.prism.protos.Signer.prototype.addNames = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.io.iohk.prism.protos.Signer.prototype.clearNamesList = function() {
  this.setNamesList([]);
};


/**
 * repeated string surnames = 2;
 * @return {!Array<string>}
 */
proto.io.iohk.prism.protos.Signer.prototype.getSurnamesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/** @param {!Array<string>} value */
proto.io.iohk.prism.protos.Signer.prototype.setSurnamesList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.io.iohk.prism.protos.Signer.prototype.addSurnames = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.io.iohk.prism.protos.Signer.prototype.clearSurnamesList = function() {
  this.setSurnamesList([]);
};


/**
 * optional string role = 3;
 * @return {string}
 */
proto.io.iohk.prism.protos.Signer.prototype.getRole = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.io.iohk.prism.protos.Signer.prototype.setRole = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string did = 4;
 * @return {string}
 */
proto.io.iohk.prism.protos.Signer.prototype.getDid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.io.iohk.prism.protos.Signer.prototype.setDid = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string title = 5;
 * @return {string}
 */
proto.io.iohk.prism.protos.Signer.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.io.iohk.prism.protos.Signer.prototype.setTitle = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.io.iohk.prism.protos.SubjectData.repeatedFields_ = [1,2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.iohk.prism.protos.SubjectData.prototype.toObject = function(opt_includeInstance) {
  return proto.io.iohk.prism.protos.SubjectData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.iohk.prism.protos.SubjectData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.prism.protos.SubjectData.toObject = function(includeInstance, msg) {
  var f, obj = {
    namesList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f,
    surnamesList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f,
    dateofbirth: (f = msg.getDateofbirth()) && common_models_pb.Date.toObject(includeInstance, f),
    iddocument: (f = msg.getIddocument()) && proto.io.iohk.prism.protos.PersonalId.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.iohk.prism.protos.SubjectData}
 */
proto.io.iohk.prism.protos.SubjectData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.iohk.prism.protos.SubjectData;
  return proto.io.iohk.prism.protos.SubjectData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.iohk.prism.protos.SubjectData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.iohk.prism.protos.SubjectData}
 */
proto.io.iohk.prism.protos.SubjectData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addNames(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addSurnames(value);
      break;
    case 3:
      var value = new common_models_pb.Date;
      reader.readMessage(value,common_models_pb.Date.deserializeBinaryFromReader);
      msg.setDateofbirth(value);
      break;
    case 4:
      var value = new proto.io.iohk.prism.protos.PersonalId;
      reader.readMessage(value,proto.io.iohk.prism.protos.PersonalId.deserializeBinaryFromReader);
      msg.setIddocument(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.iohk.prism.protos.SubjectData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.iohk.prism.protos.SubjectData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.iohk.prism.protos.SubjectData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.prism.protos.SubjectData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNamesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
  f = message.getSurnamesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getDateofbirth();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      common_models_pb.Date.serializeBinaryToWriter
    );
  }
  f = message.getIddocument();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.io.iohk.prism.protos.PersonalId.serializeBinaryToWriter
    );
  }
};


/**
 * repeated string names = 1;
 * @return {!Array<string>}
 */
proto.io.iohk.prism.protos.SubjectData.prototype.getNamesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/** @param {!Array<string>} value */
proto.io.iohk.prism.protos.SubjectData.prototype.setNamesList = function(value) {
  jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.io.iohk.prism.protos.SubjectData.prototype.addNames = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.io.iohk.prism.protos.SubjectData.prototype.clearNamesList = function() {
  this.setNamesList([]);
};


/**
 * repeated string surnames = 2;
 * @return {!Array<string>}
 */
proto.io.iohk.prism.protos.SubjectData.prototype.getSurnamesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/** @param {!Array<string>} value */
proto.io.iohk.prism.protos.SubjectData.prototype.setSurnamesList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.io.iohk.prism.protos.SubjectData.prototype.addSurnames = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.io.iohk.prism.protos.SubjectData.prototype.clearSurnamesList = function() {
  this.setSurnamesList([]);
};


/**
 * optional Date dateOfBirth = 3;
 * @return {?proto.io.iohk.prism.protos.Date}
 */
proto.io.iohk.prism.protos.SubjectData.prototype.getDateofbirth = function() {
  return /** @type{?proto.io.iohk.prism.protos.Date} */ (
    jspb.Message.getWrapperField(this, common_models_pb.Date, 3));
};


/** @param {?proto.io.iohk.prism.protos.Date|undefined} value */
proto.io.iohk.prism.protos.SubjectData.prototype.setDateofbirth = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.io.iohk.prism.protos.SubjectData.prototype.clearDateofbirth = function() {
  this.setDateofbirth(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.io.iohk.prism.protos.SubjectData.prototype.hasDateofbirth = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional PersonalId idDocument = 4;
 * @return {?proto.io.iohk.prism.protos.PersonalId}
 */
proto.io.iohk.prism.protos.SubjectData.prototype.getIddocument = function() {
  return /** @type{?proto.io.iohk.prism.protos.PersonalId} */ (
    jspb.Message.getWrapperField(this, proto.io.iohk.prism.protos.PersonalId, 4));
};


/** @param {?proto.io.iohk.prism.protos.PersonalId|undefined} value */
proto.io.iohk.prism.protos.SubjectData.prototype.setIddocument = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.io.iohk.prism.protos.SubjectData.prototype.clearIddocument = function() {
  this.setIddocument(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.io.iohk.prism.protos.SubjectData.prototype.hasIddocument = function() {
  return jspb.Message.getField(this, 4) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.iohk.prism.protos.PersonalId.prototype.toObject = function(opt_includeInstance) {
  return proto.io.iohk.prism.protos.PersonalId.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.iohk.prism.protos.PersonalId} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.prism.protos.PersonalId.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    documenttype: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.iohk.prism.protos.PersonalId}
 */
proto.io.iohk.prism.protos.PersonalId.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.iohk.prism.protos.PersonalId;
  return proto.io.iohk.prism.protos.PersonalId.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.iohk.prism.protos.PersonalId} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.iohk.prism.protos.PersonalId}
 */
proto.io.iohk.prism.protos.PersonalId.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {!proto.io.iohk.prism.protos.IdDocumentType} */ (reader.readEnum());
      msg.setDocumenttype(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.iohk.prism.protos.PersonalId.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.iohk.prism.protos.PersonalId.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.iohk.prism.protos.PersonalId} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.prism.protos.PersonalId.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDocumenttype();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.io.iohk.prism.protos.PersonalId.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.io.iohk.prism.protos.PersonalId.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional IdDocumentType documentType = 2;
 * @return {!proto.io.iohk.prism.protos.IdDocumentType}
 */
proto.io.iohk.prism.protos.PersonalId.prototype.getDocumenttype = function() {
  return /** @type {!proto.io.iohk.prism.protos.IdDocumentType} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.io.iohk.prism.protos.IdDocumentType} value */
proto.io.iohk.prism.protos.PersonalId.prototype.setDocumenttype = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.io.iohk.prism.protos.IssuerSentCredential.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.io.iohk.prism.protos.IssuerSentCredential.ValueCase = {
  VALUE_NOT_SET: 0,
  ALPHACREDENTIAL: 1,
  CREDENTIAL: 2
};

/**
 * @return {proto.io.iohk.prism.protos.IssuerSentCredential.ValueCase}
 */
proto.io.iohk.prism.protos.IssuerSentCredential.prototype.getValueCase = function() {
  return /** @type {proto.io.iohk.prism.protos.IssuerSentCredential.ValueCase} */(jspb.Message.computeOneofCase(this, proto.io.iohk.prism.protos.IssuerSentCredential.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.iohk.prism.protos.IssuerSentCredential.prototype.toObject = function(opt_includeInstance) {
  return proto.io.iohk.prism.protos.IssuerSentCredential.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.iohk.prism.protos.IssuerSentCredential} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.prism.protos.IssuerSentCredential.toObject = function(includeInstance, msg) {
  var f, obj = {
    alphacredential: (f = msg.getAlphacredential()) && proto.io.iohk.prism.protos.AlphaCredential.toObject(includeInstance, f),
    credential: (f = msg.getCredential()) && proto.io.iohk.prism.protos.Credential.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.iohk.prism.protos.IssuerSentCredential}
 */
proto.io.iohk.prism.protos.IssuerSentCredential.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.iohk.prism.protos.IssuerSentCredential;
  return proto.io.iohk.prism.protos.IssuerSentCredential.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.iohk.prism.protos.IssuerSentCredential} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.iohk.prism.protos.IssuerSentCredential}
 */
proto.io.iohk.prism.protos.IssuerSentCredential.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.io.iohk.prism.protos.AlphaCredential;
      reader.readMessage(value,proto.io.iohk.prism.protos.AlphaCredential.deserializeBinaryFromReader);
      msg.setAlphacredential(value);
      break;
    case 2:
      var value = new proto.io.iohk.prism.protos.Credential;
      reader.readMessage(value,proto.io.iohk.prism.protos.Credential.deserializeBinaryFromReader);
      msg.setCredential(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.iohk.prism.protos.IssuerSentCredential.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.iohk.prism.protos.IssuerSentCredential.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.iohk.prism.protos.IssuerSentCredential} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.prism.protos.IssuerSentCredential.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAlphacredential();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.io.iohk.prism.protos.AlphaCredential.serializeBinaryToWriter
    );
  }
  f = message.getCredential();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.io.iohk.prism.protos.Credential.serializeBinaryToWriter
    );
  }
};


/**
 * optional AlphaCredential alphaCredential = 1;
 * @return {?proto.io.iohk.prism.protos.AlphaCredential}
 */
proto.io.iohk.prism.protos.IssuerSentCredential.prototype.getAlphacredential = function() {
  return /** @type{?proto.io.iohk.prism.protos.AlphaCredential} */ (
    jspb.Message.getWrapperField(this, proto.io.iohk.prism.protos.AlphaCredential, 1));
};


/** @param {?proto.io.iohk.prism.protos.AlphaCredential|undefined} value */
proto.io.iohk.prism.protos.IssuerSentCredential.prototype.setAlphacredential = function(value) {
  jspb.Message.setOneofWrapperField(this, 1, proto.io.iohk.prism.protos.IssuerSentCredential.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.io.iohk.prism.protos.IssuerSentCredential.prototype.clearAlphacredential = function() {
  this.setAlphacredential(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.io.iohk.prism.protos.IssuerSentCredential.prototype.hasAlphacredential = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Credential credential = 2;
 * @return {?proto.io.iohk.prism.protos.Credential}
 */
proto.io.iohk.prism.protos.IssuerSentCredential.prototype.getCredential = function() {
  return /** @type{?proto.io.iohk.prism.protos.Credential} */ (
    jspb.Message.getWrapperField(this, proto.io.iohk.prism.protos.Credential, 2));
};


/** @param {?proto.io.iohk.prism.protos.Credential|undefined} value */
proto.io.iohk.prism.protos.IssuerSentCredential.prototype.setCredential = function(value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.io.iohk.prism.protos.IssuerSentCredential.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.io.iohk.prism.protos.IssuerSentCredential.prototype.clearCredential = function() {
  this.setCredential(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.io.iohk.prism.protos.IssuerSentCredential.prototype.hasCredential = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.iohk.prism.protos.Credential.prototype.toObject = function(opt_includeInstance) {
  return proto.io.iohk.prism.protos.Credential.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.iohk.prism.protos.Credential} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.prism.protos.Credential.toObject = function(includeInstance, msg) {
  var f, obj = {
    typeid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    credentialdocument: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.iohk.prism.protos.Credential}
 */
proto.io.iohk.prism.protos.Credential.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.iohk.prism.protos.Credential;
  return proto.io.iohk.prism.protos.Credential.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.iohk.prism.protos.Credential} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.iohk.prism.protos.Credential}
 */
proto.io.iohk.prism.protos.Credential.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTypeid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCredentialdocument(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.iohk.prism.protos.Credential.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.iohk.prism.protos.Credential.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.iohk.prism.protos.Credential} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.prism.protos.Credential.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTypeid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCredentialdocument();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string typeId = 1;
 * @return {string}
 */
proto.io.iohk.prism.protos.Credential.prototype.getTypeid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.io.iohk.prism.protos.Credential.prototype.setTypeid = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string credentialDocument = 2;
 * @return {string}
 */
proto.io.iohk.prism.protos.Credential.prototype.getCredentialdocument = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.io.iohk.prism.protos.Credential.prototype.setCredentialdocument = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.iohk.prism.protos.HolderSentCredential.prototype.toObject = function(opt_includeInstance) {
  return proto.io.iohk.prism.protos.HolderSentCredential.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.iohk.prism.protos.HolderSentCredential} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.prism.protos.HolderSentCredential.toObject = function(includeInstance, msg) {
  var f, obj = {
    credential: (f = msg.getCredential()) && proto.io.iohk.prism.protos.AlphaCredential.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.iohk.prism.protos.HolderSentCredential}
 */
proto.io.iohk.prism.protos.HolderSentCredential.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.iohk.prism.protos.HolderSentCredential;
  return proto.io.iohk.prism.protos.HolderSentCredential.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.iohk.prism.protos.HolderSentCredential} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.iohk.prism.protos.HolderSentCredential}
 */
proto.io.iohk.prism.protos.HolderSentCredential.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.io.iohk.prism.protos.AlphaCredential;
      reader.readMessage(value,proto.io.iohk.prism.protos.AlphaCredential.deserializeBinaryFromReader);
      msg.setCredential(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.iohk.prism.protos.HolderSentCredential.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.iohk.prism.protos.HolderSentCredential.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.iohk.prism.protos.HolderSentCredential} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.prism.protos.HolderSentCredential.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCredential();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.io.iohk.prism.protos.AlphaCredential.serializeBinaryToWriter
    );
  }
};


/**
 * optional AlphaCredential credential = 1;
 * @return {?proto.io.iohk.prism.protos.AlphaCredential}
 */
proto.io.iohk.prism.protos.HolderSentCredential.prototype.getCredential = function() {
  return /** @type{?proto.io.iohk.prism.protos.AlphaCredential} */ (
    jspb.Message.getWrapperField(this, proto.io.iohk.prism.protos.AlphaCredential, 1));
};


/** @param {?proto.io.iohk.prism.protos.AlphaCredential|undefined} value */
proto.io.iohk.prism.protos.HolderSentCredential.prototype.setCredential = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.io.iohk.prism.protos.HolderSentCredential.prototype.clearCredential = function() {
  this.setCredential(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.io.iohk.prism.protos.HolderSentCredential.prototype.hasCredential = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.iohk.prism.protos.ProofRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.io.iohk.prism.protos.ProofRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.iohk.prism.protos.ProofRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.prism.protos.ProofRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    typeid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    connectiontoken: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.iohk.prism.protos.ProofRequest}
 */
proto.io.iohk.prism.protos.ProofRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.iohk.prism.protos.ProofRequest;
  return proto.io.iohk.prism.protos.ProofRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.iohk.prism.protos.ProofRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.iohk.prism.protos.ProofRequest}
 */
proto.io.iohk.prism.protos.ProofRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTypeid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setConnectiontoken(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.iohk.prism.protos.ProofRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.iohk.prism.protos.ProofRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.iohk.prism.protos.ProofRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.prism.protos.ProofRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTypeid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getConnectiontoken();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string typeId = 1;
 * @return {string}
 */
proto.io.iohk.prism.protos.ProofRequest.prototype.getTypeid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.io.iohk.prism.protos.ProofRequest.prototype.setTypeid = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string connectionToken = 2;
 * @return {string}
 */
proto.io.iohk.prism.protos.ProofRequest.prototype.getConnectiontoken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.io.iohk.prism.protos.ProofRequest.prototype.setConnectiontoken = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.io.iohk.prism.protos.AtalaMessage.oneofGroups_ = [[1,2,3]];

/**
 * @enum {number}
 */
proto.io.iohk.prism.protos.AtalaMessage.MessageCase = {
  MESSAGE_NOT_SET: 0,
  ISSUERSENTCREDENTIAL: 1,
  HOLDERSENTCREDENTIAL: 2,
  PROOFREQUEST: 3
};

/**
 * @return {proto.io.iohk.prism.protos.AtalaMessage.MessageCase}
 */
proto.io.iohk.prism.protos.AtalaMessage.prototype.getMessageCase = function() {
  return /** @type {proto.io.iohk.prism.protos.AtalaMessage.MessageCase} */(jspb.Message.computeOneofCase(this, proto.io.iohk.prism.protos.AtalaMessage.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.iohk.prism.protos.AtalaMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.io.iohk.prism.protos.AtalaMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.iohk.prism.protos.AtalaMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.prism.protos.AtalaMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    issuersentcredential: (f = msg.getIssuersentcredential()) && proto.io.iohk.prism.protos.IssuerSentCredential.toObject(includeInstance, f),
    holdersentcredential: (f = msg.getHoldersentcredential()) && proto.io.iohk.prism.protos.HolderSentCredential.toObject(includeInstance, f),
    proofrequest: (f = msg.getProofrequest()) && proto.io.iohk.prism.protos.ProofRequest.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.iohk.prism.protos.AtalaMessage}
 */
proto.io.iohk.prism.protos.AtalaMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.iohk.prism.protos.AtalaMessage;
  return proto.io.iohk.prism.protos.AtalaMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.iohk.prism.protos.AtalaMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.iohk.prism.protos.AtalaMessage}
 */
proto.io.iohk.prism.protos.AtalaMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.io.iohk.prism.protos.IssuerSentCredential;
      reader.readMessage(value,proto.io.iohk.prism.protos.IssuerSentCredential.deserializeBinaryFromReader);
      msg.setIssuersentcredential(value);
      break;
    case 2:
      var value = new proto.io.iohk.prism.protos.HolderSentCredential;
      reader.readMessage(value,proto.io.iohk.prism.protos.HolderSentCredential.deserializeBinaryFromReader);
      msg.setHoldersentcredential(value);
      break;
    case 3:
      var value = new proto.io.iohk.prism.protos.ProofRequest;
      reader.readMessage(value,proto.io.iohk.prism.protos.ProofRequest.deserializeBinaryFromReader);
      msg.setProofrequest(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.iohk.prism.protos.AtalaMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.iohk.prism.protos.AtalaMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.iohk.prism.protos.AtalaMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.prism.protos.AtalaMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIssuersentcredential();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.io.iohk.prism.protos.IssuerSentCredential.serializeBinaryToWriter
    );
  }
  f = message.getHoldersentcredential();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.io.iohk.prism.protos.HolderSentCredential.serializeBinaryToWriter
    );
  }
  f = message.getProofrequest();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.io.iohk.prism.protos.ProofRequest.serializeBinaryToWriter
    );
  }
};


/**
 * optional IssuerSentCredential issuerSentCredential = 1;
 * @return {?proto.io.iohk.prism.protos.IssuerSentCredential}
 */
proto.io.iohk.prism.protos.AtalaMessage.prototype.getIssuersentcredential = function() {
  return /** @type{?proto.io.iohk.prism.protos.IssuerSentCredential} */ (
    jspb.Message.getWrapperField(this, proto.io.iohk.prism.protos.IssuerSentCredential, 1));
};


/** @param {?proto.io.iohk.prism.protos.IssuerSentCredential|undefined} value */
proto.io.iohk.prism.protos.AtalaMessage.prototype.setIssuersentcredential = function(value) {
  jspb.Message.setOneofWrapperField(this, 1, proto.io.iohk.prism.protos.AtalaMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.io.iohk.prism.protos.AtalaMessage.prototype.clearIssuersentcredential = function() {
  this.setIssuersentcredential(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.io.iohk.prism.protos.AtalaMessage.prototype.hasIssuersentcredential = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional HolderSentCredential holderSentCredential = 2;
 * @return {?proto.io.iohk.prism.protos.HolderSentCredential}
 */
proto.io.iohk.prism.protos.AtalaMessage.prototype.getHoldersentcredential = function() {
  return /** @type{?proto.io.iohk.prism.protos.HolderSentCredential} */ (
    jspb.Message.getWrapperField(this, proto.io.iohk.prism.protos.HolderSentCredential, 2));
};


/** @param {?proto.io.iohk.prism.protos.HolderSentCredential|undefined} value */
proto.io.iohk.prism.protos.AtalaMessage.prototype.setHoldersentcredential = function(value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.io.iohk.prism.protos.AtalaMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.io.iohk.prism.protos.AtalaMessage.prototype.clearHoldersentcredential = function() {
  this.setHoldersentcredential(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.io.iohk.prism.protos.AtalaMessage.prototype.hasHoldersentcredential = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional ProofRequest proofRequest = 3;
 * @return {?proto.io.iohk.prism.protos.ProofRequest}
 */
proto.io.iohk.prism.protos.AtalaMessage.prototype.getProofrequest = function() {
  return /** @type{?proto.io.iohk.prism.protos.ProofRequest} */ (
    jspb.Message.getWrapperField(this, proto.io.iohk.prism.protos.ProofRequest, 3));
};


/** @param {?proto.io.iohk.prism.protos.ProofRequest|undefined} value */
proto.io.iohk.prism.protos.AtalaMessage.prototype.setProofrequest = function(value) {
  jspb.Message.setOneofWrapperField(this, 3, proto.io.iohk.prism.protos.AtalaMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.io.iohk.prism.protos.AtalaMessage.prototype.clearProofrequest = function() {
  this.setProofrequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.io.iohk.prism.protos.AtalaMessage.prototype.hasProofrequest = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * @enum {number}
 */
proto.io.iohk.prism.protos.IssuerType = {
  UNIVERSITY: 0,
  SCHOOL: 1
};

/**
 * @enum {number}
 */
proto.io.iohk.prism.protos.IdDocumentType = {
  NATIONALIDCARD: 0,
  PASSPORT: 1
};

goog.object.extend(exports, proto.io.iohk.prism.protos);
