/* eslint-disable */
// source: cstore_api.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var cstore_models_pb = require('./cstore_models_pb.js');
goog.object.extend(proto, cstore_models_pb);
goog.exportSymbol('proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdRequest', null, global);
goog.exportSymbol('proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdResponse', null, global);
goog.exportSymbol('proto.io.iohk.atala.prism.protos.GetStoredCredentialsForRequest', null, global);
goog.exportSymbol('proto.io.iohk.atala.prism.protos.GetStoredCredentialsForResponse', null, global);
goog.exportSymbol('proto.io.iohk.atala.prism.protos.StoreCredentialRequest', null, global);
goog.exportSymbol('proto.io.iohk.atala.prism.protos.StoreCredentialResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.iohk.atala.prism.protos.StoreCredentialRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.iohk.atala.prism.protos.StoreCredentialRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.io.iohk.atala.prism.protos.StoreCredentialRequest.displayName = 'proto.io.iohk.atala.prism.protos.StoreCredentialRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.iohk.atala.prism.protos.StoreCredentialResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.iohk.atala.prism.protos.StoreCredentialResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.io.iohk.atala.prism.protos.StoreCredentialResponse.displayName = 'proto.io.iohk.atala.prism.protos.StoreCredentialResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.iohk.atala.prism.protos.GetStoredCredentialsForRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.iohk.atala.prism.protos.GetStoredCredentialsForRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.io.iohk.atala.prism.protos.GetStoredCredentialsForRequest.displayName = 'proto.io.iohk.atala.prism.protos.GetStoredCredentialsForRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.iohk.atala.prism.protos.GetStoredCredentialsForResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.io.iohk.atala.prism.protos.GetStoredCredentialsForResponse.repeatedFields_, null);
};
goog.inherits(proto.io.iohk.atala.prism.protos.GetStoredCredentialsForResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.io.iohk.atala.prism.protos.GetStoredCredentialsForResponse.displayName = 'proto.io.iohk.atala.prism.protos.GetStoredCredentialsForResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdRequest.displayName = 'proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdResponse.displayName = 'proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.iohk.atala.prism.protos.StoreCredentialRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.io.iohk.atala.prism.protos.StoreCredentialRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.iohk.atala.prism.protos.StoreCredentialRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.atala.prism.protos.StoreCredentialRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    connectionid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    encodedsignedcredential: jspb.Message.getFieldWithDefault(msg, 2, ""),
    credentialexternalid: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.iohk.atala.prism.protos.StoreCredentialRequest}
 */
proto.io.iohk.atala.prism.protos.StoreCredentialRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.iohk.atala.prism.protos.StoreCredentialRequest;
  return proto.io.iohk.atala.prism.protos.StoreCredentialRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.iohk.atala.prism.protos.StoreCredentialRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.iohk.atala.prism.protos.StoreCredentialRequest}
 */
proto.io.iohk.atala.prism.protos.StoreCredentialRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setConnectionid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setEncodedsignedcredential(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setCredentialexternalid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.iohk.atala.prism.protos.StoreCredentialRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.iohk.atala.prism.protos.StoreCredentialRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.iohk.atala.prism.protos.StoreCredentialRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.atala.prism.protos.StoreCredentialRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getConnectionid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getEncodedsignedcredential();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getCredentialexternalid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string connectionId = 1;
 * @return {string}
 */
proto.io.iohk.atala.prism.protos.StoreCredentialRequest.prototype.getConnectionid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.io.iohk.atala.prism.protos.StoreCredentialRequest} returns this
 */
proto.io.iohk.atala.prism.protos.StoreCredentialRequest.prototype.setConnectionid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string encodedSignedCredential = 2;
 * @return {string}
 */
proto.io.iohk.atala.prism.protos.StoreCredentialRequest.prototype.getEncodedsignedcredential = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.io.iohk.atala.prism.protos.StoreCredentialRequest} returns this
 */
proto.io.iohk.atala.prism.protos.StoreCredentialRequest.prototype.setEncodedsignedcredential = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string credentialExternalId = 3;
 * @return {string}
 */
proto.io.iohk.atala.prism.protos.StoreCredentialRequest.prototype.getCredentialexternalid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.io.iohk.atala.prism.protos.StoreCredentialRequest} returns this
 */
proto.io.iohk.atala.prism.protos.StoreCredentialRequest.prototype.setCredentialexternalid = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.iohk.atala.prism.protos.StoreCredentialResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.io.iohk.atala.prism.protos.StoreCredentialResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.iohk.atala.prism.protos.StoreCredentialResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.atala.prism.protos.StoreCredentialResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.iohk.atala.prism.protos.StoreCredentialResponse}
 */
proto.io.iohk.atala.prism.protos.StoreCredentialResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.iohk.atala.prism.protos.StoreCredentialResponse;
  return proto.io.iohk.atala.prism.protos.StoreCredentialResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.iohk.atala.prism.protos.StoreCredentialResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.iohk.atala.prism.protos.StoreCredentialResponse}
 */
proto.io.iohk.atala.prism.protos.StoreCredentialResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.iohk.atala.prism.protos.StoreCredentialResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.iohk.atala.prism.protos.StoreCredentialResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.iohk.atala.prism.protos.StoreCredentialResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.atala.prism.protos.StoreCredentialResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.iohk.atala.prism.protos.GetStoredCredentialsForRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.io.iohk.atala.prism.protos.GetStoredCredentialsForRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.iohk.atala.prism.protos.GetStoredCredentialsForRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.atala.prism.protos.GetStoredCredentialsForRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    individualid: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.iohk.atala.prism.protos.GetStoredCredentialsForRequest}
 */
proto.io.iohk.atala.prism.protos.GetStoredCredentialsForRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.iohk.atala.prism.protos.GetStoredCredentialsForRequest;
  return proto.io.iohk.atala.prism.protos.GetStoredCredentialsForRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.iohk.atala.prism.protos.GetStoredCredentialsForRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.iohk.atala.prism.protos.GetStoredCredentialsForRequest}
 */
proto.io.iohk.atala.prism.protos.GetStoredCredentialsForRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setIndividualid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.iohk.atala.prism.protos.GetStoredCredentialsForRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.iohk.atala.prism.protos.GetStoredCredentialsForRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.iohk.atala.prism.protos.GetStoredCredentialsForRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.atala.prism.protos.GetStoredCredentialsForRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIndividualid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string individualId = 1;
 * @return {string}
 */
proto.io.iohk.atala.prism.protos.GetStoredCredentialsForRequest.prototype.getIndividualid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.io.iohk.atala.prism.protos.GetStoredCredentialsForRequest} returns this
 */
proto.io.iohk.atala.prism.protos.GetStoredCredentialsForRequest.prototype.setIndividualid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.io.iohk.atala.prism.protos.GetStoredCredentialsForResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.iohk.atala.prism.protos.GetStoredCredentialsForResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.io.iohk.atala.prism.protos.GetStoredCredentialsForResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.iohk.atala.prism.protos.GetStoredCredentialsForResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.atala.prism.protos.GetStoredCredentialsForResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    credentialsList: jspb.Message.toObjectList(msg.getCredentialsList(),
    cstore_models_pb.StoredSignedCredential.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.iohk.atala.prism.protos.GetStoredCredentialsForResponse}
 */
proto.io.iohk.atala.prism.protos.GetStoredCredentialsForResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.iohk.atala.prism.protos.GetStoredCredentialsForResponse;
  return proto.io.iohk.atala.prism.protos.GetStoredCredentialsForResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.iohk.atala.prism.protos.GetStoredCredentialsForResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.iohk.atala.prism.protos.GetStoredCredentialsForResponse}
 */
proto.io.iohk.atala.prism.protos.GetStoredCredentialsForResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new cstore_models_pb.StoredSignedCredential;
      reader.readMessage(value,cstore_models_pb.StoredSignedCredential.deserializeBinaryFromReader);
      msg.addCredentials(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.iohk.atala.prism.protos.GetStoredCredentialsForResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.iohk.atala.prism.protos.GetStoredCredentialsForResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.iohk.atala.prism.protos.GetStoredCredentialsForResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.atala.prism.protos.GetStoredCredentialsForResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCredentialsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      cstore_models_pb.StoredSignedCredential.serializeBinaryToWriter
    );
  }
};


/**
 * repeated StoredSignedCredential credentials = 1;
 * @return {!Array<!proto.io.iohk.atala.prism.protos.StoredSignedCredential>}
 */
proto.io.iohk.atala.prism.protos.GetStoredCredentialsForResponse.prototype.getCredentialsList = function() {
  return /** @type{!Array<!proto.io.iohk.atala.prism.protos.StoredSignedCredential>} */ (
    jspb.Message.getRepeatedWrapperField(this, cstore_models_pb.StoredSignedCredential, 1));
};


/**
 * @param {!Array<!proto.io.iohk.atala.prism.protos.StoredSignedCredential>} value
 * @return {!proto.io.iohk.atala.prism.protos.GetStoredCredentialsForResponse} returns this
*/
proto.io.iohk.atala.prism.protos.GetStoredCredentialsForResponse.prototype.setCredentialsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.io.iohk.atala.prism.protos.StoredSignedCredential=} opt_value
 * @param {number=} opt_index
 * @return {!proto.io.iohk.atala.prism.protos.StoredSignedCredential}
 */
proto.io.iohk.atala.prism.protos.GetStoredCredentialsForResponse.prototype.addCredentials = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.io.iohk.atala.prism.protos.StoredSignedCredential, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.io.iohk.atala.prism.protos.GetStoredCredentialsForResponse} returns this
 */
proto.io.iohk.atala.prism.protos.GetStoredCredentialsForResponse.prototype.clearCredentialsList = function() {
  return this.setCredentialsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdRequest}
 */
proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdRequest;
  return proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdRequest}
 */
proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    latestcredentialexternalid: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdResponse}
 */
proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdResponse;
  return proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdResponse}
 */
proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setLatestcredentialexternalid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLatestcredentialexternalid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string latestCredentialExternalId = 1;
 * @return {string}
 */
proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdResponse.prototype.getLatestcredentialexternalid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdResponse} returns this
 */
proto.io.iohk.atala.prism.protos.GetLatestCredentialExternalIdResponse.prototype.setLatestcredentialexternalid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


goog.object.extend(exports, proto.io.iohk.atala.prism.protos);
