@startuml
title Connect with a person

actor Issuer
participant "Management Console" as ManagementConsole
participant "IOHK Server API" as ServerAPI
participant "Prism Mobile Wallet" as MobileWallet
actor Holder

group Connect to the holder's mobile wallet
    Issuer -> ManagementConsole : Create a person
    ManagementConsole -> ServerAPI : Create a person
    ServerAPI -> ManagementConsole : Person created
    ManagementConsole -> Issuer : Person created

    Issuer -> ManagementConsole : Generate connection token
    ManagementConsole -> ServerAPI : Generate connection token
    ServerAPI -> ManagementConsole : Connection token
    ManagementConsole -> Issuer : Connection token as QR Code

    Issuer -> Holder : Share QR Code
    Holder -> MobileWallet : Scan QR Code
    MobileWallet -> ServerAPI : Find QR Code details
    ServerAPI -> MobileWallet : Issuer details
    MobileWallet -> Holder : Asks to confirm connection
    Holder -> MobileWallet : Confirm connection
    MobileWallet -> ServerAPI : Accept connection
    ServerAPI -> MobileWallet : Connected
    MobileWallet -> Holder : Connected
end
@enduml