@startuml
title Issue credential

actor Issuer
participant "Management Console" as ManagementConsole
participant "Prism Browser Wallet" as BrowserWallet
participant "IOHK Server API" as ServerAPI

group Issue the credential to the group
    Issuer -> ManagementConsole : Issue credential group
    ManagementConsole -> BrowserWallet : Issue credential group
    BrowserWallet -> Issuer : Asks to confirm the operation
    Issuer -> BrowserWallet : Confirm
    BrowserWallet -> BrowserWallet : Sign credentials
    BrowserWallet -> ServerAPI : Store and issue credentials
    ServerAPI -> ServerAPI : Add issuance proof to Cardano
    ServerAPI -> ServerAPI : Store the signed credentials
    ServerAPI -> BrowserWallet : Credentials issued
    BrowserWallet -> ManagementConsole : Credentials issued
    ManagementConsole -> Issuer : Credentials issued
end
@enduml
