@startuml
title Revoke credential

actor Issuer
participant "Management Console" as ManagementConsole
participant "Prism Browser Wallet" as BrowserWallet
participant "IOHK Server API" as ServerAPI

group Revoke the credential
    Issuer -> ManagementConsole : Find credentials
    ManagementConsole -> Issuer : Credentials
    Issuer -> ManagementConsole : Choose a credential to revoke
    ManagementConsole -> BrowserWallet : Revoke credential
    BrowserWallet -> Issuer : Asks to confirm the operation
    Issuer -> BrowserWallet : Confirm
    BrowserWallet -> BrowserWallet : Sign revoke operation
    BrowserWallet -> ServerAPI : Submit revocation
    ServerAPI -> ServerAPI : Add revocation proof to Cardano
    ServerAPI -> BrowserWallet : Credential revoked
    BrowserWallet -> ManagementConsole : Credential revoked
    ManagementConsole -> Issuer : Credentials revoked
end
@enduml
