# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

source 'https://cdn.cocoapods.org'
source 'https://github.com/itegulov/Specs.git'

target 'prism-ios-wallet' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for prism-ios-wallet

  # UI components
  pod 'Presentr', '~> 1.9.0' 
  pod 'MaterialComponents/Chips'
  # Linter
  pod 'SwiftLint'
  # Acuant
  pod 'AcuantiOSSDKV11', '~> 11.5.1' 
  pod 'AcuantiOSSDKV11/AcuantCamera'
   
  post_install do |installer|
      installer.pods_project.targets.each do |target|
         target.build_configurations.each do |config|
           if !['Starscream'].include? target.name
             config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
           end
         end
      end
     installer.pods_project.targets.each do |target|
       if ['AcuantiOSSDKV11', 'KeychainAccess', 'Socket.IO-Client-Swift', 'Starscream' 'SwiftyJSON'].include? target.name
         target.build_configurations.each do |config|
           config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
         end
       end
     end
   end
  
  target 'prism-ios-walletTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'prism-ios-walletUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  

end
