# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

source 'https://cdn.cocoapods.org'
source 'https://github.com/itegulov/Specs.git'

target 'prism-ios-wallet' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for prism-ios-wallet

  # Server calls
  pod 'Alamofire', '~> 4.8.2'
  pod 'AlamofireImage', '~> 3.5'
  pod 'AlamofireObjectMapper', '~> 5.2'
  pod 'ObjectMapper', '~> 3.1'
  pod 'SwiftGRPC', '~> 0.10.0'
  pod 'SwiftProtobuf', '~> 1.7.0'
  # Logger
  pod 'SwiftyBeaver', '~> 1.7.0'
  # UI components
  pod 'Tabman', '~> 2.6'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'Presentr', '~> 1.9.0' 
  pod 'Toast-Swift', '~> 5.0.0'
  pod 'MaterialComponents/Chips'
  # Firebase
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
  pod 'Firebase/Performance'
  # Payments
  pod 'BraintreeDropIn', '~> 7.5.0'
  # Mnemonics
  pod 'BitcoinKit', '~> 1.1.0'
  # Linter
  pod 'SwiftLint'
  # PRISM SDK
  pod 'crypto', :path => '../prism-kotlin-sdk/crypto'
  
  target 'prism-ios-walletTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'prism-ios-walletUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
