load("@io_bazel_rules_scala//scala:scala.bzl", "scala_library", "scala_test")

scala_library(
    name = "data",
    srcs = glob(["**/*.scala"], exclude=["test/**/*"]),
    deps = [ ],
    visibility = ["//visibility:public"]
)

