@startuml
skinparam backgroundColor #EEEBDC

title Indy - Verify credential

actor Student
actor Employer
actor University

Student -> Employer : Share credential
Employer -> University : Ask for the credential validity
University -> University : Check the digital signatures
University -> University : Check revocation registry
University -> Employer : Credential verification result
@enduml
