
' Support for C4 is bundled with PlantUML as part of its "stdlib".
' For more about the stdlib, see also https://plantuml.com/stdlib

!include <c4/C4.puml>
!include <c4/C4_Context.puml>
!include <c4/C4_Container.puml>
!include <c4/C4_Component.puml>

hide <<person>> stereotype
hide <<container>> stereotype
hide <<boundary>> stereotype
hide <<external_system>> stereotype
