@startuml
digraph prism_nomad_on_premise_deployment {
  # this is deployment dependency graph:
  # - nodes with no dependencies are the first to be deployed.
  # - nodes with dependencies can be deployed only after its dependencies.
  # - "a -> b" means that "b" can be deployed only when "a" is ready.
  # - a topological order can allow us to deploy services in parallel and in the right order.

  # prism is the whole deployment without considering how to talk to it from the public internet
  prism


  # consul is needed for service discovery
  consul_1
  consul_2
  consul_3
  consul_cluster

  consul_1 -> consul_cluster
  consul_2 -> consul_cluster
  consul_3 -> consul_cluster

  # nomad
  nomad_server_1
  nomad_server_2
  nomad_server_3
  nomad_servers

  nomad_client_1
  nomad_client_2
  nomad_client_N
  nomad_clients

  nomad_cluster
  nomad_server_1 -> nomad_servers
  nomad_server_2 -> nomad_servers
  nomad_server_3 -> nomad_servers
  nomad_client_1 -> nomad_clients
  nomad_client_2 -> nomad_clients
  nomad_client_N -> nomad_clients

  nomad_servers -> nomad_client_1
  nomad_servers -> nomad_client_2
  nomad_servers -> nomad_client_N
  nomad_servers -> nomad_cluster
  nomad_clients -> nomad_cluster

  consul_cluster -> nomad_server_1
  consul_cluster -> nomad_server_2
  consul_cluster -> nomad_server_3
  nomad_cluster -> prism
}
@enduml
