apiVersion: v1
entries:
  prism-node:
    - apiVersion: v2
      appVersion: 2.4.0
      created: "2024-05-22T11:20:33.990568475Z"
      description: A Helm chart for deploying prism-node
      digest: 692bef9312fbdfcf8dd885c06d69bfa0ba5fc201086c5af26ddd2b932c1934c0
      name: prism-node
      type: application
      urls:
        - https://raw.githubusercontent.com/input-output-hk/atala-prism/main/infrastructure/charts/prism-node-0.1.0.tgz
      version: 0.1.0
generated: "2024-05-22T11:20:33.990000234Z"
