# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'credentials-verification-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for credentials-verification-iOS
  pod 'SwiftGRPC'
  pod 'SwiftProtobuf'
  
  target 'credentials-verification-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'credentials-verification-iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
