# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'credentials-verification-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for credentials-verification-iOS

  # Server calls
  pod 'Alamofire', '~> 4.8.2'
  pod 'AlamofireImage', '~> 3.5'
  pod 'AlamofireObjectMapper', '~> 5.2'
  pod 'ObjectMapper', '~> 3.1'
  pod 'SwiftGRPC', '~> 0.10.0'
  pod 'SwiftProtobuf', '~> 1.7.0'
  # Logger
  pod 'SwiftyBeaver', '~> 1.7.0'
  # UI components
  pod 'Tabman', '~> 2.6'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'Presentr', '~> 1.9.0' 
  pod 'Toast-Swift', '~> 5.0.0'
  # Firebase
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.14.0'
  pod 'Firebase/Analytics', '~> 6.13.0'
  pod 'Firebase/Performance', '~> 6.13.0'
  # Payments
  pod 'BraintreeDropIn', '~> 7.5.0'
  # Mnemonics
  pod 'BitcoinKit', '~> 1.1.0'

  
  target 'credentials-verification-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'credentials-verification-iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
