@startuml
title Create a credential group

actor Issuer
participant "Management Console" as ManagementConsole
participant "IOHK Server API" as ServerAPI

group Create a credential group
    Issuer -> ManagementConsole : Create a credential group
    ManagementConsole -> Issuer : Asks to choose the credential type
    Issuer -> ManagementConsole : Choose credential type
    ManagementConsole -> Issuer : Asks to choose the credential\ndetails for the whole group
    Issuer -> ManagementConsole : Credential details
    ManagementConsole -> Issuer : Asks to choose the persons\ninvolved in the credential
    Issuer -> ManagementConsole : Choose the person to issue the credential to
    ManagementConsole -> Issuer : Asks for the person details required by the credential
    Issuer -> ManagementConsole : Person details
    ManagementConsole -> ServerAPI : Create credential group
    ServerAPI -> ManagementConsole : Credential group created
    ManagementConsole -> Issuer : Credential group created
end
@enduml
