---
#- import_role:
#    name: nginx

- name: Ensure gatling directory exists with correct permissions
  file:
    path: "{{gatling_dir}}"
    state: directory
    mode: 0775

- name: Download Gatling
  get_url:
    url: "{{ gatling_url }}"
    dest: "{{ gatling_dir }}/{{gatling_archive}}"

- name: Extract Gatling
  unarchive:
    remote_src: yes
    src: "{{gatling_dir}}/{{gatling_archive}}"
    dest: "{{gatling_dir}}"

- name: Remove Gatling archive
  file:
    path: "{{gatling_dir}}/{{gatling_archive}}"
    state: absent

- name: Push the performance test
  copy:
    src: "{{playbook_dir}}/../perf-test/src/it/scala/io/iohk/cef/PerfSimulation.scala"
    dest: "{{gatling_dir}}/{{gatling_base}}/user-files/simulations"

- name: Run the performance test
  shell: "{{gatling_dir}}/{{gatling_base}}/bin/gatling.sh -s io.iohk.cef.PerfSimulation"

- name: Copy nginx config for results directory
  become: True
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf

- name: Restart nginx
  become: True
  service:
    name: nginx
    state: restarted
