name: "Managment Console PR Workflow"
on:
  pull_request:
    paths:
      - 'prism-management-console-web/src/**'
      - "prism-management-console-web/package.json"

env:
  GITHUB_TOKEN: ${{ secrets.ATALA_GITHUB_TOKEN }}

jobs:
  build-prism-management-console-web:
    name: "Build Prism MC Web"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install protoc
        run: |
          archive=protoc-"3.11.4"-linux-x86_64
          curl -O -L https://github.com/protocolbuffers/protobuf/releases/download/v"3.11.4"/$archive.zip
          sudo unzip -d '/usr/local' $archive.zip 'bin/*' 'include/*'
          rm -rf ${archive}.zip

      - name: Install protoc-gen-grpc-web
        run: |
          archive=protoc-gen-grpc-web-1.0.7-linux-x86_64
          curl -O -L https://github.com/grpc/grpc-web/releases/download/1.0.7/$archive
          chmod +x $archive
          sudo mv $archive /usr/local/bin/protoc-gen-grpc-web

      - name: Move to target folder then run tests
        run: cd prism-management-console-web && ./web-testing-script.sh

      - name: Move to target folder then run linting validation script
        run: cd prism-management-console-web && ./web-linting-validation-script.sh
